import type { ComponentMetadata } from '@solidaris/contracts';

export const AffiliateOverviewCardMetadata: ComponentMetadata = {
  component: {
    name: 'AffiliateOverviewCard',
    category: 'molecules',
    description:
      'iSHARE affiliate audit summary card with horizontal avatar layout, status split button, info tags, copyable identifiers, and primary action.',
    type: 'display',
    path: 'libs/ui/src/lib/affiliate-overview-card/affiliate-overview-card.component.ts',
    primeNgComponent: 'Card, SplitButton, Button, ToggleButton',
    bemBlock: 'c-affiliate-overview-card',
    itcssLayer: '06-components',
    scssPath: 'libs/styles/src/06-components/_components.affiliate-overview-card.scss',
    created: new Date().toISOString(),
    modified: new Date().toISOString(),
  },
  usage: {
    useCases: [
      'Affiliate audit result summary (Dossier Affilié)',
      'Post-search affiliate detail panel',
      'Status-driven affiliate overview with corrective actions',
    ],
    commonPatterns: [
      {
        name: 'Audit result card',
        description:
          'Show affiliate identity, info tags, and copyable identifiers after a successful lookup.',
        composition:
          '<sds-affiliate-overview-card variant="in-order" [title]="name" [avatarInitials]="initials" [infoTags]="tags" [identifiers]="ids" />',
      },
      {
        name: 'Action required',
        description:
          'Surface a non-blocking audit issue with a warn split button and identifier chips.',
        composition:
          '<sds-affiliate-overview-card variant="warning" [statusAction]="action" [infoTags]="tags" [identifiers]="ids" />',
      },
    ],
    antiPatterns: [
      {
        scenario: 'Full-page form layout',
        reason: 'The card is a read-only summary container, not a form shell.',
        alternative: 'Use form-field groups inside a dedicated form card.',
      },
      {
        scenario: 'Inline table of many affiliates',
        reason: 'Identifier chips are designed for a single affiliate snapshot.',
        alternative: 'Use a data table component for multi-row listings.',
      },
    ],
  },
  accessibility: {
    wcagLevel: 'AA',
    ariaAttributes: [
      'aria-labelledby on article (title h2) when loaded',
      'aria-label + aria-busy on article when loading',
      'aria-pressed on filterable info-tag toggle buttons (p-togglebutton, native role=button)',
      'aria-label on copy identifier buttons (Copier {label})',
      'expandAriaLabel on status split button menu toggle (Afficher le menu pour {label})',
      'aria-hidden on bullet separators, shortcut badge, and skeleton lines',
    ],
    contrastRequirements: [
      'Status split button must include visible French label text — not colour alone.',
      'Info tag buttons must pair label and value text — not colour alone.',
    ],
  },
  tokens: {
    consumed: [
      '--sds-color-affiliate-overview-card-accent-success',
      '--sds-color-affiliate-overview-card-accent-warning',
      '--sds-color-affiliate-overview-card-accent-danger',
      '--sds-color-affiliate-overview-card-bg-default',
      '--sds-affiliate-overview-card-bg-gradient-angle',
      '--sds-affiliate-overview-card-bg-gradient-stop',
      '--sds-color-affiliate-overview-card-bg-warning-gradient-start',
      '--sds-color-affiliate-overview-card-bg-warning',
      '--sds-color-affiliate-overview-card-bg-danger-gradient-start',
      '--sds-color-affiliate-overview-card-bg-danger',
      '--sds-color-affiliate-overview-card-bg-in-order-gradient-start',
      '--sds-color-affiliate-overview-card-bg-in-order',
      '--sds-color-affiliate-overview-card-info-tag-bg',
      '--sds-color-affiliate-overview-card-info-tag-text',
      '--sds-color-affiliate-overview-card-metadata-text',
      '--sds-color-affiliate-overview-card-metadata-separator',
      '--sds-color-affiliate-overview-card-shortcut-badge-bg',
      '--sds-color-affiliate-overview-card-shortcut-badge-text',
      '--sds-text-affiliate-overview-card-shortcut-badge-size',
      '--sds-text-affiliate-overview-card-shortcut-badge-weight',
      '--sds-text-affiliate-overview-card-shortcut-badge-line-height',
      '--sds-color-affiliate-overview-card-skeleton-bg',
      '--sds-size-affiliate-overview-card-accent-width',
      '--sds-size-affiliate-overview-card-padding',
      '--sds-space-affiliate-overview-card-avatar-gap',
      '--sds-space-affiliate-overview-card-header-gap',
      '--sds-space-affiliate-overview-card-header-inner-gap',
      '--sds-space-affiliate-overview-card-metadata-gap',
      '--sds-space-affiliate-overview-card-info-tag-padding-inline',
      '--sds-space-affiliate-overview-card-info-tag-padding-block',
      '--sds-space-affiliate-overview-card-shortcut-badge-padding-inline',
      '--sds-space-affiliate-overview-card-shortcut-badge-padding-block',
      '--sds-size-affiliate-overview-card-metadata-icon',
      '--sds-size-affiliate-overview-card-skeleton-avatar',
      '--sds-color-drawer-border',
      '--sds-color-affiliate-overview-card-border',
      '--sds-color-orange-50',
      '--sds-color-danger-subtle',
      '--sds-color-success-subtle',
      '--sds-color-surface-0',
      '--sds-color-info-tag-text',
      '--sds-color-metadata-chip-text',
      '--sds-color-text',
      '--sds-color-text-muted',
      '--sds-color-surface-border',
      '--sds-radius-none',
      '--spacing-0-25',
      '--spacing-0-5',
      '--spacing-1',
      '--spacing-1-5',
      '--spacing-2',
      '--spacing-5',
      '--text-heading-lg-family',
      '--text-heading-lg-size',
      '--text-heading-lg-weight',
      '--text-heading-lg-line-height',
      '--text-heading-lg-spacing',
      '--text-label-sm-family',
      '--text-label-sm-size',
      '--text-label-sm-weight',
      '--text-label-sm-line-height',
      '--text-label-sm-spacing',
      '--text-body-sm-family',
      '--text-body-sm-size',
      '--text-body-sm-weight',
      '--text-body-sm-line-height',
      '--text-body-sm-spacing',
      '--p-card-body-padding',
      '--p-card-border-color',
      '--p-card-background',
      '--p-card-border-radius',
      '--p-card-shadow',
    ],
  },
  aiHints: {
    priority: 'high',
    context:
      'Primary affiliate summary card for iSHARE audit flows. Horizontal layout per Figma 507:7910. Variants: default, in-order, warning, danger.',
    selectionCriteria: {
      'variant default': 'Neutral lookup result without status emphasis',
      'variant in-order': 'Affiliate audit passes — success accent',
      'variant warning': 'Action required — warn split button',
      'variant danger': 'Critical issue — danger split button',
    },
    keywords: ['affiliate', 'audit', 'overview', 'NISS', 'NSI', 'status', 'metadata', 'iSHARE'],
  },
  props: [
    { name: 'title', type: 'string', required: true, description: 'Affiliate display name (card heading)' },
    { name: 'avatarInitials', type: 'string', required: false, default: "''", description: 'Initials fallback for the Plectrum avatar' },
    { name: 'avatarGender', type: 'PlectrumAvatarGender', required: false, default: 'female', description: 'Illustrated avatar gender passed to sds-plectrum-avatar' },
    { name: 'avatarVariant', type: 'PlectrumAvatarVariant', required: false, default: '1', description: 'Illustrated avatar variant passed to sds-plectrum-avatar' },
    { name: 'variant', type: 'AffiliateOverviewCardVariant', required: false, default: 'default', description: 'Severity-driven card treatment' },
    { name: 'loading', type: 'boolean', required: false, default: 'false', description: 'Skeleton placeholder state' },
  ],
  examples: [],
};
