import type { ComponentMetadata } from '@solidaris/contracts';

export const AffiliateOverviewCardMetadata: ComponentMetadata = {
  component: {
    name: 'AffiliateOverviewCard',
    category: 'molecules',
    description:
      'iSHARE affiliate audit summary card with horizontal avatar layout, outlined status button, info tags, copyable identifiers, and primary action.',
    type: 'display',
    path: 'libs/ui/src/lib/affiliate-overview-card/affiliate-overview-card.component.ts',
    primeNgComponent: 'Card, Button, SelectButton',
    bemBlock: 'c-affiliate-overview-card',
    itcssLayer: '06-components',
    scssPath:
      'libs/styles/src/06-components/_components.affiliate-overview-card.scss',
    created: new Date().toISOString(),
    modified: new Date().toISOString(),
  },
  usage: {
    useCases: [
      'Affiliate audit result summary (Dossier Affilié)',
      'Post-search affiliate detail panel',
      'Status-driven affiliate overview with corrective actions',
    ],
    commonPatterns: [
      {
        name: 'Audit result card',
        description:
          'Show affiliate identity, info tags, and copyable identifiers after a successful lookup.',
        composition:
          '<(pds|app|lib)-affiliate-overview-card variant="in-order" [title]="name" [avatarInitials]="initials" [infoTags]="tags" [identifiers]="ids" />',
      },
      {
        name: 'Action required',
        description:
          'Surface a non-blocking audit issue with a warn status button and identifier chips.',
        composition:
          '<(pds|app|lib)-affiliate-overview-card variant="default" [statusAction]="{ label: \'C4 non reçu\', tagValue: \'C4\', severity: \'warn\' }" [infoTags]="tags" [identifiers]="ids" />',
      },
    ],
    antiPatterns: [
      {
        scenario: 'Full-page form layout',
        reason: 'The card is a read-only summary container, not a form shell.',
        alternative: 'Use form-field groups inside a dedicated form card.',
      },
      {
        scenario: 'Inline table of many affiliates',
        reason:
          'Identifier chips are designed for a single affiliate snapshot.',
        alternative: 'Use a data table component for multi-row listings.',
      },
    ],
  },
  accessibility: {
    wcagLevel: 'AA',
    ariaAttributes: [
      'aria-labelledby on article (title h2) when loaded',
      'aria-label + aria-busy on article when loading',
      'aria-pressed on filterable info-tag select button options (p-selectbutton inner toggle buttons, native role=button)',
      'Alt+A — trigger primary action when primaryAction.shortcut is set (skipped in editable fields)',
      'aria-keyshortcuts on primary action button when shortcut badge is shown',
      'aria-label on copy identifier buttons (Copier {label})',
      'aria-label on status action button (from statusAction.ariaLabel or label)',
      'aria-hidden on bullet separators, shortcut badge, and skeleton lines',
    ],
    contrastRequirements: [
      'Status button must include visible French label text — not colour alone.',
      'Info tag buttons must pair label and value text — not colour alone.',
    ],
  },
  tokens: {
    consumed: [
      '--pds-color-affiliate-overview-card-bg-default',
      '--pds-affiliate-overview-card-bg-gradient-angle',
      '--pds-affiliate-overview-card-bg-gradient-stop',
      '--pds-color-affiliate-overview-card-bg-warning-gradient-start',
      '--pds-color-affiliate-overview-card-bg-warning',
      '--pds-color-affiliate-overview-card-bg-danger-gradient-start',
      '--pds-color-affiliate-overview-card-bg-danger',
      '--pds-color-affiliate-overview-card-bg-in-order-gradient-start',
      '--pds-color-affiliate-overview-card-bg-in-order',
      '--pds-color-affiliate-overview-card-info-tag-bg',
      '--pds-color-affiliate-overview-card-info-tag-text',
      '--pds-color-affiliate-overview-card-metadata-text',
      '--pds-color-affiliate-overview-card-metadata-separator',
      '--pds-color-affiliate-overview-card-shortcut-badge-bg',
      '--pds-color-affiliate-overview-card-shortcut-badge-text',
      '--pds-text-affiliate-overview-card-shortcut-badge-size',
      '--pds-text-affiliate-overview-card-shortcut-badge-weight',
      '--pds-text-affiliate-overview-card-shortcut-badge-line-height',
      '--pds-color-affiliate-overview-card-skeleton-bg',
      '--pds-size-affiliate-overview-card-padding',
      '--pds-space-affiliate-overview-card-avatar-gap',
      '--pds-space-affiliate-overview-card-header-gap',
      '--pds-space-affiliate-overview-card-header-inner-gap',
      '--pds-space-affiliate-overview-card-metadata-gap',
      '--pds-space-affiliate-overview-card-info-tag-padding-inline',
      '--pds-space-affiliate-overview-card-info-tag-padding-block',
      '--pds-space-affiliate-overview-card-shortcut-badge-padding-inline',
      '--pds-space-affiliate-overview-card-shortcut-badge-padding-block',
      '--pds-size-affiliate-overview-card-metadata-icon',
      '--pds-size-affiliate-overview-card-skeleton-avatar',
      '--pds-color-panel-border',
      '--pds-color-orange-50',
      '--pds-color-danger-subtle',
      '--pds-color-success-subtle',
      '--pds-color-surface-0',
      '--pds-color-info-tag-text',
      '--pds-color-metadata-chip-text',
      '--pds-color-text',
      '--pds-color-text-muted',
      '--pds-color-surface-border',
      '--pds-radius-none',
      '--spacing-0-25',
      '--spacing-0-5',
      '--spacing-1',
      '--spacing-1-5',
      '--spacing-2',
      '--spacing-5',
      '--text-heading-lg-family',
      '--text-heading-lg-size',
      '--text-heading-lg-weight',
      '--text-heading-lg-line-height',
      '--text-heading-lg-spacing',
      '--text-label-sm-family',
      '--text-label-sm-size',
      '--text-label-sm-weight',
      '--text-label-sm-line-height',
      '--text-label-sm-spacing',
      '--text-body-sm-family',
      '--text-body-sm-size',
      '--text-body-sm-weight',
      '--text-body-sm-line-height',
      '--text-body-sm-spacing',
      '--p-card-body-padding',
      '--p-card-border-color',
      '--p-card-background',
      '--p-card-border-radius',
      '--p-card-shadow',
    ],
  },
  aiHints: {
    priority: 'high',
    context:
      'Primary affiliate summary card for iSHARE audit flows. Horizontal layout per Figma 507:7910. Card gradient driven by statusAction.severity; variant input is fallback when no status action.',
    selectionCriteria: {
      'statusAction.severity success':
        'Affiliate audit passes — in-order gradient + success button',
      'statusAction.severity warn':
        'Action required — warning gradient + warn button',
      'statusAction.severity danger':
        'Critical issue — danger gradient + danger button',
      'variant in-order (no statusAction)':
        'Success gradient via variant fallback only',
      'variant default (no statusAction)':
        'Neutral lookup result without status emphasis',
    },
    keywords: [
      'affiliate',
      'audit',
      'overview',
      'NISS',
      'NSI',
      'status',
      'metadata',
      'iSHARE',
    ],
  },
  props: [
    {
      name: 'title',
      type: 'string',
      required: true,
      description: 'Affiliate display name (card heading)',
    },
    {
      name: 'avatarInitials',
      type: 'string',
      required: false,
      default: "''",
      description: 'Initials fallback for the Plectrum avatar',
    },
    {
      name: 'avatarGender',
      type: 'PlectrumAvatarGender',
      required: false,
      default: 'female',
      description: 'Illustrated avatar gender passed to pds-plectrum-avatar',
    },
    {
      name: 'avatarVariant',
      type: 'PlectrumAvatarVariant',
      required: false,
      default: '1',
      description: 'Illustrated avatar variant passed to pds-plectrum-avatar',
    },
    {
      name: 'variant',
      type: 'AffiliateOverviewCardVariant',
      required: false,
      default: 'default',
      description: 'Fallback card treatment when statusAction is absent',
    },
    {
      name: 'statusAction',
      type: 'AffiliateOverviewStatusAction | null',
      required: false,
      default: 'null',
      description:
        'Outlined status button config. severity (success | warn | danger) drives card gradient when set.',
    },
    {
      name: 'loading',
      type: 'boolean',
      required: false,
      default: 'false',
      description: 'Skeleton placeholder state',
    },
  ],
  examples: [],
};
