import type { ComponentMetadata } from '@solidaris/contracts';

export const ListMetadata: ComponentMetadata = {
  component: {
    name: 'List',
    category: 'molecules',
    description:
      'Grouped or flat entry list built on PrimeNG Tree node templates with card-row chrome. Journey mode (groups non-null) adds expandable group headers and a timeline gutter under them; flat mode lists full-width entry cards.',
    type: 'display',
    path: 'libs/ui/src/lib/list/list.component.ts',
    primeNgComponent: 'Tree',
    bemBlock: 'c-list',
    itcssLayer: '06-components',
    scssPath: 'libs/styles/src/06-components/_components.list.scss',
    figmaUrl: 'https://www.figma.com/design/wmG7Dx9R7I6oJBUV3NYlTi/Custom-components?node-id=107-3675',
    created: '2026-06-07',
    modified: '2026-09-09',
  },
  governance: {
    status: 'core',
    owner: 'design-system',
    note: 'PrimeNG Tree variant. Rows are generic entries; apps supply icons and copy.',
  },
  usage: {
    useCases: [
      'Journey-grouped entries (parcours) with expandable tree groups and a timeline',
      'Flat document or entry listing without grouping',
      'A follow-up (suivi) panel of card rows with status and count tags',
    ],
    commonPatterns: [
      {
        name: 'Journey grouped list',
        description:
          'Pass non-null groups with expandedGroupIds for tree group nodes and nested document rows.',
        composition:
          '<(pds|app|lib)-list [groups]="groups" [expandedGroupIds]="expandedIds" (expandedGroupIdsChange)="expandedIds = $event" />',
      },
      {
        name: 'Flat document list',
        description: 'Pass groups=null and flat document items for a flat tree of document nodes.',
        composition: '<(pds|app|lib)-list [groups]="null" [items]="documents" />',
      },
    ],
    antiPatterns: [
      {
        scenario: 'Mixing groups and flat items in one binding',
        reason: 'The mode is decided by groups alone — null is flat, non-null is journey — so items is ignored in journey mode.',
        alternative: 'Shape the data into groups or into flat items before binding, never both.',
      },
      {
        scenario: 'A full-page data table of dense columns',
        reason: 'Rows are entry summaries (icon, title, status, tags), not tabular data.',
        alternative: 'Use p-table for dense columnar listings.',
      },
    ],
  },
  anatomy: [
    { part: 'c-list', role: 'Region host — c-list--journey or c-list--flat modifier, is-loading + aria-busy while loading' },
    { part: 'c-list__header-row', role: 'Optional title + count badge above the tree (showHeader)' },
    { part: 'p-tree', role: 'PrimeNG tree — group and entry node templates, native toggler' },
    { part: 'c-list__item--group', role: 'Expandable journey group header with folder icon and start / end dates' },
    { part: 'c-list__item--entry', role: 'Document / entry card row — c-list__item--selected when selected' },
    { part: 'c-list__timeline-*', role: 'Journey gutter sprites (decorative)' },
    { part: 'p-tag / pButton', role: 'Status and count tags — a tag with deep-link targets is a button' },
    { part: 'c-list__footnote', role: 'Optional footnote button below the tree' },
    { part: 'p-popover', role: 'Target picker (role="listbox") when a count tag has several targets' },
  ],
  behavior: {
    states: ['journey', 'flat', 'group-expanded', 'group-collapsed', 'row-default', 'row-hover', 'row-selected', 'loading'],
    interactions: [
      'Journey mode (groups non-null): chevron toggler on group headers and a timeline gutter (--pds-size-list-timeline-gutter) on child entry rows; flat mode renders full-width entry cards without chevron or timeline',
      'Expansion is controlled: expandedGroupIds in, expandedGroupIdsChange out — the native tree toggler, a click or Enter / Space on the group header all toggle it',
      'Selecting an entry emits itemClick; selectedItemId takes precedence over item.selected and expands the parent group once when it moves programmatically',
      'Entry rows: neutral border by default, primary border on hover, primary border plus elevation (--pds-shadow-list-row-selected) and an accented bold title when selected; group headers get no hover / selected chrome',
      'Count tags with one target emit tagTargetClick directly; with several targets they open a p-popover listbox to pick one',
      'loading=true replaces the tree with three PrimeNG skeleton rows and sets aria-busy',
    ],
  },
  composition: {
    nestedComponents: ['Tree', 'Tag', 'Button', 'Skeleton', 'Popover'],
  },
  accessibility: {
    wcagLevel: 'AA',
    ariaAttributes: [
      'Host is role="region" with an aria-label ("Suivi des documents" / "Opvolging van documenten"); aria-busy is set while loading',
      'PrimeNG Tree supplies treeitem semantics for groups and entries; the group togglers carry a locale aria-label',
      'Selection is aria-selected on the PrimeNG treeitem — row cards are not nested buttons',
      'The sort icon and the timeline sprites are aria-hidden; the target picker is a role="listbox" of role="option" items named by the tag aria-label',
    ],
    keyboardSupport: [
      'PrimeNG Tree keyboard model: Up / Down move between rows, Right / Left expand or collapse a group, Enter or Space selects an entry (itemClick) or toggles a group',
      'Count tags with targets and the footnote are native buttons in the tab order; Enter or Space activates them and picks an option in the popover',
    ],
    contrastRequirements: [
      'Status and footer tags must include visible label text — not colour alone',
      'The selected entry uses the accent colour and bold weight in addition to aria-selected',
    ],
  },
  tokens: {
    consumed: [
      '--pds-color-list-bg',
      '--pds-color-panel-border',
      '--pds-color-list-section-title',
      '--pds-color-list-count-badge-bg',
      '--pds-color-list-count-badge-text',
      '--pds-color-list-row-bg',
      '--pds-color-list-row-border',
      '--pds-color-list-row-hover-border',
      '--pds-color-list-row-selected-border',
      '--pds-color-list-title-text',
      '--pds-color-list-title-accent',
      '--pds-color-list-icon',
      '--pds-color-divider',
      '--pds-color-list-date-label',
      '--pds-color-list-date-value',
      '--pds-color-list-timeline-line',
      '--pds-color-list-timeline-marker',
      '--pds-color-list-timeline-marker-border',
      '--pds-color-list-skeleton-bg',
      '--pds-size-list-icon',
      '--pds-size-list-timeline-gutter',
      '--pds-size-list-timeline-marker',
      '--pds-size-list-count-badge-min',
      '--pds-border-width-list',
      '--pds-border-width-list-row',
      '--pds-border-width-list-selected',
      '--pds-shadow-list-row-selected',
      '--pds-transition-list-row',
      '--pds-opacity-divider',
      '--pds-radius-xl',
      '--pds-radius-sm',
      '--pds-disabled-opacity',
    ],
  },
  aiHints: {
    priority: 'high',
    context:
      'Primary document list for iSHARE affiliate details. Journey ON: PrimeNG Tree with group/document card templates (Figma 2:125 row states). Journey OFF: flat document tree. Native tree toggler for expand/collapse.',
    selectionCriteria: {
      'groups non-null': 'Journey / parcours grouped tree mode',
      'groups null': 'Flat document tree without group nodes',
    },
    keywords: ['list', 'documents', 'journey', 'parcours', 'tree', 'affiliate', 'iSHARE'],
  },
  props: [
    {
      name: 'groups',
      type: 'ListGroup[] | null',
      required: false,
      default: 'null',
      description: 'Non-null enables journey grouped mode; null enables flat mode.',
    },
    {
      name: 'items',
      type: 'ListItem[]',
      required: false,
      default: '[]',
      description: 'Flat document rows when groups is null.',
    },
    { name: 'loading', type: 'boolean', required: false, default: 'false', description: 'Skeleton placeholder state.' },
    { name: 'showHeader', type: 'boolean', required: false, default: 'true', description: 'When false, the list region heading is omitted.' },
    {
      name: 'expandedGroupIds',
      type: 'string[]',
      required: false,
      default: '[]',
      description: 'IDs of expanded journey groups (controlled state).',
    },
    {
      name: 'selectedItemId',
      type: 'string | null',
      required: false,
      default: 'null',
      description: 'ID of the selected document row — takes precedence over doc.selected.',
    },
    { name: 'footnote', type: 'string | null', required: false, default: 'null', description: 'Optional footnote rendered below the tree.' },
    { name: 'expandedGroupIdsChange', type: 'output<string[]>', required: false, description: 'Emitted when a journey group is expanded or collapsed.' },
    { name: 'footnoteClick', type: 'output<void>', required: false, description: 'Emitted when the footnote is activated.' },
    { name: 'itemClick', type: 'output<ListItem>', required: false, description: 'Emitted when a document row is activated.' },
    { name: 'tagTargetClick', type: 'output<{ doc: ListEntryItem; tag: ListEntryTag; target: ListEntryTagTarget }>', required: false, description: 'Emitted when a count-tag deep-link target is chosen.' },
  ],
  examples: [],
};
