import fs from 'node:fs';
import path from 'node:path';
import { asset, configAt, format, hash, packageJson, packageRoot, projectPath, readJson } from './common.mjs';
import { expand } from './process.mjs';

const manifestPath = '.plectrum/managed.json';
const slug = (value) => value.toLowerCase().replaceAll(' ', '-');

/** Role text and baseline instructions resolve their commands from the installed process contract. */
export function guidance(contract = asset('process.json')) {
  const roles = Object.fromEntries(Object.entries(readJson(path.join(packageRoot, 'roles.json'))).map(([name, body]) => [name, expand(body, contract)]));
  const baseline = `# Plectrum application instructions\n\nRead .plectrum/config.json and node_modules/@solidaris-danielbodigil/pds-devkit/rules/consumer.md. The installed package owns the catalogue, process ${contract.version}, schemas and roles. ${expand('Start with `{{command:consumerCatalogue}}`, create local components autonomously with `{{command:consumerScaffold}}`, and run `{{command:consumerCheck}}`.', contract)} Core approval is required only for central submission. Do not edit node_modules or use central-repository paths. Keep team notes outside files generated by \`plectrum init/update\`.\n`;
  return { roles, baseline };
}

function adapters() {
  const contract = asset('process.json');
  const { roles, baseline } = guidance(contract);
  const run = (id) => contract.commands[id].command.replace(/ \[[^\]]*\]/g, '');
  const result = {
    '.ai/rules/plectrum-managed.md': baseline,
    '.ai/skills/plectrum-component/SKILL.md': `# Build a Plectrum application component\n\nRead ../../rules/plectrum-managed.md and the installed devkit rules/consumer.md. Search the installed catalogue and PrimeNG first. A local component may be created without Core approval. Generate it with ${run('consumerScaffold')}, complete its story, test, metadata and evidence, then run the local checks. Submit to Core only when sharing is desired and a merged central proposal has approved intake.\n`,
    '.ai/protocols/plectrum.md': `# Plectrum protocol\n\nThe application owns local components. The installed process contract at node_modules/@solidaris-danielbodigil/pds-devkit/assets/process.json owns CLI syntax and exchange schemas. Use package scripts for Storybook, tests and CI. A candidate submission rereads the central decision; local quality does not imply central publication.\n`,
    '.cursor/rules/plectrum.mdc': `---\ndescription: Plectrum application workflow\nalwaysApply: true\n---\n\n${baseline}`,
    '.github/instructions/plectrum.instructions.md': `---\napplyTo: '**/*'\n---\n\n${baseline}`,
    '.github/workflows/plectrum-checks.yml': `name: Plectrum checks\non:\n  pull_request:\n  push:\n    branches: [main]\npermissions:\n  contents: read\n  packages: read\njobs:\n  plectrum:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v5\n        with:\n          node-version: '24'\n          cache: npm\n          registry-url: https://npm.pkg.github.com\n          scope: '@solidaris-danielbodigil'\n      - run: npm ci\n        env:\n          NODE_AUTH_TOKEN: \${{ secrets.GITHUB_TOKEN }}\n      - run: npx playwright install --with-deps chromium\n      - run: ${run('consumerCheck')}\n      - run: npm run build\n      - run: npm run pds:test:unit\n      - run: npm run pds:build-storybook\n      - run: npm run pds:test:stories\n      - if: github.event_name == 'push'\n        run: ${run('adoptionSubmit')}\n        env:\n          GH_TOKEN: \${{ secrets.PLECTRUM_ADOPTION_TOKEN }}\n`,
  };
  for (const [name, body] of Object.entries(roles)) {
    const file = slug(name);
    result[`.cursor/agents/${file}.md`] = `---\nname: ${name}\ndescription: Plectrum ${name} role for application teams\nreadonly: false\n---\n\n${body}\n\nShared process: node_modules/@solidaris-danielbodigil/pds-devkit/assets/process.json. Consumer rules: node_modules/@solidaris-danielbodigil/pds-devkit/rules/consumer.md.\n`;
    result[`.ai/agents/${file}.md`] = `${body}\n\nShared process: node_modules/@solidaris-danielbodigil/pds-devkit/assets/process.json.\n`;
    result[`.github/agents/${file}.agent.md`] = `---\nname: ${name}\ndescription: Plectrum ${name} role for application teams\ntools:\n  - read\n  - search\n  - edit\n  - runCommands\n---\n\n${body}\n\nShared process: node_modules/@solidaris-danielbodigil/pds-devkit/assets/process.json. Consumer rules: node_modules/@solidaris-danielbodigil/pds-devkit/rules/consumer.md.\n`;
  }
  return result;
}

function desiredServers(config, editor) {
  const mcp = config.mcp ?? {};
  const endpoints = { 'plectrum-primeng': mcp.primeNg, 'plectrum-figma': mcp.figma, 'plectrum-storybook': mcp.storybook };
  return Object.fromEntries(Object.entries(endpoints).filter(([, url]) => typeof url === 'string' && /^https?:\/\//.test(url)).map(([name, url]) => [name, editor === 'cursor' ? { url } : { type: 'http', url }]));
}

export function initialize(root, args) {
  const file = projectPath(root, '.plectrum/config.json');
  if (fs.existsSync(file)) {
    console.log('Existing project config preserved. Running update.');
    return update(root);
  }
  const get = (key) => {
    const arg = args.find((a) => a.startsWith(`--${key}=`));
    const pos = args.indexOf(`--${key}`);
    return arg ? arg.slice(key.length + 3) : pos >= 0 ? args[pos + 1] : undefined;
  };
  const team = get('team');
  const application = get('application');
  const repository = get('repository');
  const project = get('project');
  if (!team || !application || !repository) throw new Error('Usage: plectrum init --team <id> --application <id> --repository <https-url>');
  if (!/^[a-z][a-z0-9-]*$/.test(team) || !/^[a-z][a-z0-9-]*$/.test(application) || !/^https?:\/\//.test(repository)) throw new Error('Use slug IDs and a full repository URL.');
  const config = {
    schemaVersion: 1, team, application, repository, ...(project ? { project } : {}),
    paths: { source: ['src'], styles: ['src/styles'], candidates: 'src/plectrum-candidates', candidateStyles: 'src/styles/06-components', localTokenFiles: [] },
    dependencies: ['@solidaris-danielbodigil/pds-ui', '@solidaris-danielbodigil/pds-plectrum', '@solidaris-danielbodigil/pds-styles'],
    mcp: { primeNg: 'https://primeng.org/mcp', figma: null, storybook: null },
    reporting: { output: '.plectrum/reports/adoption.json', enabled: true },
  };
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, format(config));
  console.log(`Created .plectrum/config.json for ${application}.`);
  try { return update(root); }
  catch (error) { fs.rmSync(file); throw error; }
}

export function update(root) {
  const config = configAt(root);
  const manifestFile = projectPath(root, manifestPath);
  const before = fs.existsSync(manifestFile) ? readJson(manifestFile) : { files: {}, servers: {} };
  const plannedFiles = adapters();
  const plans = [];
  const conflicts = [];
  for (const [relative, content] of Object.entries(plannedFiles)) {
    const file = projectPath(root, relative);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    const previousHash = before.files?.[relative];
    if (current !== null && current !== content && (!previousHash || hash(current) !== previousHash)) conflicts.push(relative);
    else plans.push({ file, content });
  }
  const serverPlans = [];
  for (const [editor, relative, key] of [['cursor', '.cursor/mcp.json', 'mcpServers'], ['vscode', '.vscode/mcp.json', 'servers']]) {
    const file = projectPath(root, relative);
    const value = fs.existsSync(file) ? readJson(file) : {};
    const servers = value[key] ?? {};
    const desired = desiredServers(config, editor);
    for (const [name, endpoint] of Object.entries(desired)) {
      const existing = servers[name];
      const previousHash = before.servers?.[`${relative}:${name}`];
      if (existing && JSON.stringify(existing) !== JSON.stringify(endpoint) && (!previousHash || hash(format(existing)) !== previousHash)) conflicts.push(`${relative}:${name}`);
      else servers[name] = endpoint;
    }
    for (const name of Object.keys(servers)) {
      if (!name.startsWith('plectrum-') || desired[name]) continue;
      const previousHash = before.servers?.[`${relative}:${name}`];
      if (previousHash && hash(format(servers[name])) === previousHash) delete servers[name];
    }
    serverPlans.push({ file, relative, value: { ...value, [key]: servers }, desired });
  }
  if (conflicts.length) throw new Error(`Managed-file conflict; no files changed:\n${conflicts.map((f) => `  ${f}`).join('\n')}\nMove custom notes to another file or restore the last generated content, then rerun plectrum update.`);
  const next = { schemaVersion: 1, toolkitVersion: packageJson.version, files: {}, servers: {} };
  let changed = 0;
  for (const { file, content } of plans) {
    const relative = path.relative(root, file).replaceAll('\\', '/');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) { fs.writeFileSync(file, content); changed++; }
    next.files[relative] = hash(content);
  }
  for (const { file, relative, value, desired } of serverPlans) {
    const content = format(value);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) { fs.writeFileSync(file, content); changed++; }
    for (const [name, endpoint] of Object.entries(desired)) next.servers[`${relative}:${name}`] = hash(format(endpoint));
  }
  const content = format(next);
  if (!fs.existsSync(manifestFile) || fs.readFileSync(manifestFile, 'utf8') !== content) fs.writeFileSync(manifestFile, content);
  console.log(`Plectrum ${packageJson.version}: ${changed} editor/CI file(s) updated; project config and unrelated files preserved.`);
  return next;
}

export function managedStatus(root) {
  const file = projectPath(root, manifestPath);
  if (!fs.existsSync(file)) return ['Missing .plectrum/managed.json'];
  const manifest = readJson(file);
  const errors = [];
  for (const [relative, digest] of Object.entries(manifest.files ?? {})) {
    const target = projectPath(root, relative);
    if (!fs.existsSync(target) || hash(fs.readFileSync(target, 'utf8')) !== digest) errors.push(`Modified managed file: ${relative}`);
  }
  for (const [identity, digest] of Object.entries(manifest.servers ?? {})) {
    const separator = identity.indexOf(':');
    const relative = identity.slice(0, separator);
    const name = identity.slice(separator + 1);
    const target = projectPath(root, relative);
    const data = fs.existsSync(target) ? readJson(target) : {};
    const server = data[relative.startsWith('.cursor/') ? 'mcpServers' : 'servers']?.[name];
    if (!server || hash(format(server)) !== digest) errors.push(`Modified managed MCP server: ${identity}`);
  }
  if (manifest.toolkitVersion !== packageJson.version) errors.push(`Adapters use toolkit ${manifest.toolkitVersion}; run plectrum update for ${packageJson.version}`);
  return errors;
}
