// Generated by npm run adoption:generate. Storybook build refreshes this file.
export const CENTRAL_ADOPTION: {
  staleAfterDays: number;
  agent: readonly { application: string; label: string; freshness: 'current' | 'stale'; observedAt: string; windowDays: number; activeDays: number; toolCalls: number; searches: number; emptySearches: number; lookups: Readonly<Record<string, number>>; commits: { total: number; reuse: number; scaffold: number; advice: number }; reused: Readonly<Record<string, number>> }[];
  localComponents: readonly { id: string; name: string; description: string; useCases: readonly string[]; reusePotential: 'none' | 'possible' | 'likely' | 'unknown'; reuseNote?: string; team: string; application: string; label: string; freshness: 'current' | 'stale' }[];
  usedIn: Readonly<Record<string, readonly { application: string; label: string; kind: 'local-demo' | 'external'; freshness: 'current' | 'stale'; observedAt: string; packageVersion: string }[]>>;
  missing: readonly { id: string; label: string; kind: 'local-demo' | 'external' }[];
  reported: readonly { id: string; label: string }[];
  retired: readonly { id: string; observedAt: string }[];
} = {
  "staleAfterDays": 14,
  "agent": [],
  "localComponents": [],
  "usedIn": {},
  "missing": [
    {
      "id": "ishare",
      "label": "iSHARE",
      "kind": "local-demo"
    },
    {
      "id": "icrm",
      "label": "iCRM",
      "kind": "local-demo"
    },
    {
      "id": "iged",
      "label": "iGED",
      "kind": "local-demo"
    }
  ],
  "reported": [],
  "retired": []
};
