// Generated by npm run adoption:generate. Storybook build refreshes this file.
export const CENTRAL_ADOPTION: {
  staleAfterDays: number;
  usedIn: Readonly<Record<string, readonly { application: string; label: string; kind: 'local-demo' | 'external'; freshness: 'current' | 'stale'; observedAt: string; packageVersion: string }[]>>;
  missing: readonly { id: string; label: string; kind: 'local-demo' | 'external' }[];
  reported: readonly { id: string; label: string }[];
  retired: readonly { id: string; observedAt: string }[];
} = {
  "staleAfterDays": 14,
  "usedIn": {},
  "missing": [
    {
      "id": "ishare",
      "label": "iSHARE",
      "kind": "local-demo"
    },
    {
      "id": "icrm",
      "label": "iCRM",
      "kind": "local-demo"
    },
    {
      "id": "iged",
      "label": "iGED",
      "kind": "local-demo"
    }
  ],
  "reported": [],
  "retired": []
};
