// Generated by tools/scripts/changelog-to-ts.mjs — do not edit by hand.

import type { ChangelogChangeset, ChangelogRelease } from './changelog.types';

export const CHANGELOG_UNRELEASED: ChangelogChangeset[] = [];

export const CHANGELOG_RELEASES: ChangelogRelease[] = [
  {
    "packageName": "@solidaris/ui",
    "version": "1.0.0",
    "changes": [
      {
        "bump": "major",
        "text": "5a886d4: Rename the three Core catalogue APIs to domain-neutral names: ListDocument* → ListEntry*, pds-affiliate-overview-card → pds-profile-card, pds-affiliate-detail-drawer → pds-profile-drawer. Keyword-to-icon inference moves to iSHARE; ProfileDrawerData uses generalRows / contactRows / relatedMembers."
      },
      {
        "bump": "minor",
        "text": "f152b62: Promote `pds-toolbar` from Candidate (iSHARE) to Core so every application can import it."
      },
      {
        "bump": "minor",
        "text": "eb922bb: Add an optional hint on form-field and require Storybook play tests on every component. Catalogue stories, a11y reports, Chromatic, and story coverage run in CI; toolbar row/column gap classes now apply."
      },
      {
        "bump": "patch",
        "text": "f699043: Publish `@solidaris/ui`, `@solidaris/plectrum`, and `@solidaris/styles` as versioned packages (APF for the Angular libs, SCSS source for styles)."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris/plectrum",
    "version": "1.0.0",
    "changes": [
      {
        "bump": "major",
        "text": "5a886d4: Rename the three Core catalogue APIs to domain-neutral names: ListDocument* → ListEntry*, pds-affiliate-overview-card → pds-profile-card, pds-affiliate-detail-drawer → pds-profile-drawer. Keyword-to-icon inference moves to iSHARE; ProfileDrawerData uses generalRows / contactRows / relatedMembers."
      },
      {
        "bump": "minor",
        "text": "f152b62: Promote `pds-toolbar` from Candidate (iSHARE) to Core so every application can import it."
      },
      {
        "bump": "minor",
        "text": "eb922bb: Add an optional hint on form-field and require Storybook play tests on every component. Catalogue stories, a11y reports, Chromatic, and story coverage run in CI; toolbar row/column gap classes now apply."
      },
      {
        "bump": "patch",
        "text": "f699043: Publish `@solidaris/ui`, `@solidaris/plectrum`, and `@solidaris/styles` as versioned packages (APF for the Angular libs, SCSS source for styles)."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris/styles",
    "version": "1.0.0",
    "changes": [
      {
        "bump": "major",
        "text": "5a886d4: Rename the three Core catalogue APIs to domain-neutral names: ListDocument* → ListEntry*, pds-affiliate-overview-card → pds-profile-card, pds-affiliate-detail-drawer → pds-profile-drawer. Keyword-to-icon inference moves to iSHARE; ProfileDrawerData uses generalRows / contactRows / relatedMembers."
      },
      {
        "bump": "minor",
        "text": "f152b62: Promote `pds-toolbar` from Candidate (iSHARE) to Core so every application can import it."
      },
      {
        "bump": "minor",
        "text": "eb922bb: Add an optional hint on form-field and require Storybook play tests on every component. Catalogue stories, a11y reports, Chromatic, and story coverage run in CI; toolbar row/column gap classes now apply."
      },
      {
        "bump": "patch",
        "text": "f699043: Publish `@solidaris/ui`, `@solidaris/plectrum`, and `@solidaris/styles` as versioned packages (APF for the Angular libs, SCSS source for styles)."
      }
    ],
    "notes": ""
  }
];
