// Generated by tools/scripts/changelog-to-ts.mjs — do not edit by hand.

import type { ChangelogChangeset, ChangelogRelease } from './changelog.types';

export const CHANGELOG_UNRELEASED: ChangelogChangeset[] = [
  {
    "id": "plectrum-agent-advisor",
    "bumps": [
      {
        "packageName": "@solidaris-danielbodigil/pds-devkit",
        "bump": "patch"
      }
    ],
    "summary": "Application agents act as the team's first reviewer: before anything is built they check PrimeNG and the installed catalogue (use cases, anti-patterns, compositions), say when an existing component already covers the need, answer layout and UX questions, flag decisions for a designer, and recommend showing new UX early to the core team or a designer. They also know about local token files. The contribution \"implement\" step no longer lists `plectrum init`; the starter runs `plectrum bootstrap` on `npm install`."
  },
  {
    "id": "share-local-components",
    "bumps": [
      {
        "packageName": "@solidaris-danielbodigil/pds-devkit",
        "bump": "minor"
      }
    ],
    "summary": "Make local components visible to Core. The evidence checklist of a new component gets a \"Reuse potential (none / possible / likely) and why\" line. The usage report now lists the team's local components with that estimate, and Find a component shows them under a new Local scope. Each toolkit release ships the other teams' local components (`@solidaris-danielbodigil/pds-devkit/local-components`): `plectrum scaffold` lists similar ones, and the agents check them before suggesting a new component."
  }
];

export const CHANGELOG_RELEASES: ChangelogRelease[] = [
  {
    "packageName": "@solidaris-danielbodigil/pds-ui",
    "version": "2.0.4",
    "changes": [],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-ui",
    "version": "2.0.3",
    "changes": [
      {
        "bump": "patch",
        "text": "a00b0ca: Mark the v0.6 preset as deprecated while retaining it for migration comparisons. Ship Agenda font files in `pds-styles` and generate FR/NL and preset controls in application Storybook previews. Remove the test-only SCSS component."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-ui",
    "version": "2.0.2",
    "changes": [
      {
        "bump": "patch",
        "text": "c335207: Move the distributable packages to new Plectrum names so their first GitHub Packages publication can be verified as private. The earlier package names remain a public historical release."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/ui",
    "version": "2.0.1",
    "changes": [
      {
        "bump": "patch",
        "text": "6094cfa: Figma token sync 8baef65. 0 values changed, 172 added, 0 removed. Review the sync report before merging. Adjust the bump if the change is not a patch."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris/ui",
    "version": "2.0.0",
    "changes": [
      {
        "bump": "major",
        "text": "4020736: Move iSHARE-specific components out of the core entry point. Import `DelayPredictionCardComponent` and `TransactionsCicsModalComponent` from `@solidaris/ui/patterns/ishare` instead of `@solidaris/ui`. Generate runtime exports from component governance and distribution metadata. Candidates remain local. Workspace metadata imports move to the generated Storybook registry or the colocated metadata source; they are not part of the Angular runtime API."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris/ui",
    "version": "1.0.0",
    "changes": [
      {
        "bump": "major",
        "text": "5a886d4: Rename the three Core catalogue APIs to domain-neutral names: ListDocument* → ListEntry*, pds-affiliate-overview-card → pds-profile-card, pds-affiliate-detail-drawer → pds-profile-drawer. Keyword-to-icon inference moves to iSHARE; ProfileDrawerData uses generalRows / contactRows / relatedMembers."
      },
      {
        "bump": "minor",
        "text": "f152b62: Promote `pds-toolbar` from Candidate (iSHARE) to Core so every application can import it."
      },
      {
        "bump": "minor",
        "text": "eb922bb: Add an optional hint on form-field and require Storybook play tests on every component. Catalogue stories, a11y reports, Chromatic, and story coverage run in CI; toolbar row/column gap classes now apply."
      },
      {
        "bump": "patch",
        "text": "f699043: Publish `@solidaris/ui`, `@solidaris/plectrum`, and `@solidaris/styles` as versioned packages (APF for the Angular libs, SCSS source for styles)."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-plectrum",
    "version": "2.0.4",
    "changes": [],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-plectrum",
    "version": "2.0.3",
    "changes": [
      {
        "bump": "patch",
        "text": "a00b0ca: Mark the v0.6 preset as deprecated while retaining it for migration comparisons. Ship Agenda font files in `pds-styles` and generate FR/NL and preset controls in application Storybook previews. Remove the test-only SCSS component."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-plectrum",
    "version": "2.0.2",
    "changes": [
      {
        "bump": "patch",
        "text": "c335207: Move the distributable packages to new Plectrum names so their first GitHub Packages publication can be verified as private. The earlier package names remain a public historical release."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/plectrum",
    "version": "2.0.1",
    "changes": [
      {
        "bump": "patch",
        "text": "6094cfa: Figma token sync 8baef65. 0 values changed, 172 added, 0 removed. Review the sync report before merging. Adjust the bump if the change is not a patch."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris/plectrum",
    "version": "2.0.0",
    "changes": [],
    "notes": ""
  },
  {
    "packageName": "@solidaris/plectrum",
    "version": "1.0.0",
    "changes": [
      {
        "bump": "major",
        "text": "5a886d4: Rename the three Core catalogue APIs to domain-neutral names: ListDocument* → ListEntry*, pds-affiliate-overview-card → pds-profile-card, pds-affiliate-detail-drawer → pds-profile-drawer. Keyword-to-icon inference moves to iSHARE; ProfileDrawerData uses generalRows / contactRows / relatedMembers."
      },
      {
        "bump": "minor",
        "text": "f152b62: Promote `pds-toolbar` from Candidate (iSHARE) to Core so every application can import it."
      },
      {
        "bump": "minor",
        "text": "eb922bb: Add an optional hint on form-field and require Storybook play tests on every component. Catalogue stories, a11y reports, Chromatic, and story coverage run in CI; toolbar row/column gap classes now apply."
      },
      {
        "bump": "patch",
        "text": "f699043: Publish `@solidaris/ui`, `@solidaris/plectrum`, and `@solidaris/styles` as versioned packages (APF for the Angular libs, SCSS source for styles)."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-styles",
    "version": "2.0.4",
    "changes": [
      {
        "bump": "patch",
        "text": "c8ea036: Ship Open Sans with the styles package. The latin variable font (weights 300–800, SIL Open Font License) is in `assets/fonts/open-sans/` and loaded by `04-elements`; applications that copy the package's `assets/fonts` folder get it with Agenda, without loading Open Sans from another source."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-styles",
    "version": "2.0.3",
    "changes": [
      {
        "bump": "patch",
        "text": "a00b0ca: Mark the v0.6 preset as deprecated while retaining it for migration comparisons. Ship Agenda font files in `pds-styles` and generate FR/NL and preset controls in application Storybook previews. Remove the test-only SCSS component."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/pds-styles",
    "version": "2.0.2",
    "changes": [
      {
        "bump": "patch",
        "text": "c335207: Move the distributable packages to new Plectrum names so their first GitHub Packages publication can be verified as private. The earlier package names remain a public historical release."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris-danielbodigil/styles",
    "version": "2.0.1",
    "changes": [
      {
        "bump": "patch",
        "text": "6094cfa: Figma token sync 8baef65. 0 values changed, 172 added, 0 removed. Review the sync report before merging. Adjust the bump if the change is not a patch."
      }
    ],
    "notes": ""
  },
  {
    "packageName": "@solidaris/styles",
    "version": "2.0.0",
    "changes": [],
    "notes": ""
  },
  {
    "packageName": "@solidaris/styles",
    "version": "1.0.0",
    "changes": [
      {
        "bump": "major",
        "text": "5a886d4: Rename the three Core catalogue APIs to domain-neutral names: ListDocument* → ListEntry*, pds-affiliate-overview-card → pds-profile-card, pds-affiliate-detail-drawer → pds-profile-drawer. Keyword-to-icon inference moves to iSHARE; ProfileDrawerData uses generalRows / contactRows / relatedMembers."
      },
      {
        "bump": "minor",
        "text": "f152b62: Promote `pds-toolbar` from Candidate (iSHARE) to Core so every application can import it."
      },
      {
        "bump": "minor",
        "text": "eb922bb: Add an optional hint on form-field and require Storybook play tests on every component. Catalogue stories, a11y reports, Chromatic, and story coverage run in CI; toolbar row/column gap classes now apply."
      },
      {
        "bump": "patch",
        "text": "f699043: Publish `@solidaris/ui`, `@solidaris/plectrum`, and `@solidaris/styles` as versioned packages (APF for the Angular libs, SCSS source for styles)."
      }
    ],
    "notes": ""
  }
];
