// Generated by tools/scripts/changelog-to-ts.mjs — do not edit by hand.

import type { ChangelogChangeset, ChangelogRelease } from './changelog.types';

export const CHANGELOG_UNRELEASED: ChangelogChangeset[] = [
  {
    "id": "genericise-core-components",
    "bumps": [
      {
        "packageName": "@solidaris/ui",
        "bump": "major"
      },
      {
        "packageName": "@solidaris/plectrum",
        "bump": "major"
      },
      {
        "packageName": "@solidaris/styles",
        "bump": "major"
      }
    ],
    "summary": "Rename the three Core catalogue APIs to domain-neutral names: ListDocument* → ListEntry*, pds-affiliate-overview-card → pds-profile-card, pds-affiliate-detail-drawer → pds-profile-drawer. Keyword-to-icon inference moves to iSHARE; ProfileDrawerData uses generalRows / contactRows / relatedMembers."
  },
  {
    "id": "storybook-tests-and-form-field-hint",
    "bumps": [
      {
        "packageName": "@solidaris/ui",
        "bump": "minor"
      },
      {
        "packageName": "@solidaris/plectrum",
        "bump": "minor"
      },
      {
        "packageName": "@solidaris/styles",
        "bump": "minor"
      }
    ],
    "summary": "Add an optional hint on form-field and require Storybook play tests on every component. Catalogue stories, a11y reports, Chromatic, and story coverage run in CI; toolbar row/column gap classes now apply."
  },
  {
    "id": "wave-6-publishable-libraries",
    "bumps": [
      {
        "packageName": "@solidaris/ui",
        "bump": "patch"
      },
      {
        "packageName": "@solidaris/plectrum",
        "bump": "patch"
      },
      {
        "packageName": "@solidaris/styles",
        "bump": "patch"
      }
    ],
    "summary": "Publish `@solidaris/ui`, `@solidaris/plectrum`, and `@solidaris/styles` as versioned packages (APF for the Angular libs, SCSS source for styles)."
  }
];

export const CHANGELOG_RELEASES: ChangelogRelease[] = [];
