// Generated by npm run contracts:generate. Do not edit.
// Source: .github/workflows/ci.yml
export const CI_JOBS = [
  {
    "id": "intake-guard",
    "condition": null,
    "steps": [
      {
        "name": "Keep external candidate intake data-only",
        "run": "inline shell script",
        "advisory": false,
        "condition": "github.event_name == 'pull_request'"
      }
    ]
  },
  {
    "id": "build",
    "condition": null,
    "steps": [
      {
        "name": "Audit token drift",
        "run": "npm run tokens:audit",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Validate preset token refs",
        "run": "npm run tokens:validate-preset",
        "advisory": true,
        "condition": null
      },
      {
        "name": "Guard bare token declarations",
        "run": "npm run tokens:check-prefix",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Rebuild generated tokens (must be committed)",
        "run": "npm run tokens:build && git diff --exit-code -- libs/styles/src/01-settings/*.generated.scss libs/ui/src/storybook/tokens.generated.ts",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Rebuild token proposal (must be committed)",
        "run": "npm run tokens:propose:test && npm run tokens:propose && git diff --exit-code -- tools/tokens/proposed.dtcg.json",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Rebuild changelog feed (must be committed)",
        "run": "npm run changelog:build && git diff --exit-code -- libs/ui/src/storybook/changelog.generated.ts",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Lint token usage",
        "run": "npm run tokens:lint",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Lint layout properties in component SCSS",
        "run": "npm run lint:styles:test && npm run lint:styles",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Rebuild contracts index (must be committed)",
        "run": "npm run contracts:generate -- --check && npm run devkit:check && npm run devkit:test && npm run test:pipelines",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Validate central candidate intake and promotion",
        "run": "npm run candidate:check && npm run adoption:check",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Validate adoption reports against the PR base",
        "run": "npm run adoption:check -- --base ${{ github.event.pull_request.base.sha }}",
        "advisory": false,
        "condition": "github.event_name == 'pull_request'"
      },
      {
        "name": "Validate candidate lifecycle against the PR base",
        "run": "npm run candidate:check -- --base ${{ github.event.pull_request.base.sha }}",
        "advisory": false,
        "condition": "github.event_name == 'pull_request'"
      },
      {
        "name": "Component docs read their metadata (no hand-written copies)",
        "run": "npm run docs:check",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Metadata props match Angular inputs",
        "run": "npm run contracts:check",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Build applications",
        "run": "npm run build",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Build iGED",
        "run": "npx ng build iged --configuration=production",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Install Playwright Chromium",
        "run": "npx playwright install --with-deps chromium",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Run tests",
        "run": "npm run test:coverage",
        "advisory": false,
        "condition": null
      }
    ]
  },
  {
    "id": "pack-smoke",
    "condition": null,
    "steps": [
      {
        "name": "Install Playwright Chromium",
        "run": "npx playwright install --with-deps chromium",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Pack libraries and build a throwaway consumer app",
        "run": "npm run pack:smoke",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Verify package ownership, registry target and release artifacts",
        "run": "npm run release:check",
        "advisory": false,
        "condition": null
      }
    ]
  },
  {
    "id": "storybook-tests",
    "condition": null,
    "steps": [
      {
        "name": "Install Playwright browser",
        "run": "npx playwright install --with-deps chromium",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Build Storybook",
        "run": "npm run build-storybook:coverage",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Verify toolkit catalogue documentation routes",
        "run": "npm run contracts:docs-check",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Run story smoke, interaction, a11y and coverage tests",
        "run": "npm run test-storybook:ci",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Cross-page navigation under the Pages sub-path",
        "run": "npm run test-storybook:nav",
        "advisory": false,
        "condition": null
      }
    ]
  },
  {
    "id": "chromatic",
    "condition": "${{ vars.CHROMATIC_ENABLED == 'true' }}",
    "steps": []
  },
  {
    "id": "storybook-packed",
    "condition": null,
    "steps": [
      {
        "name": "Build packed libraries",
        "run": "npm run pack:libs",
        "advisory": false,
        "condition": null
      },
      {
        "name": "Build Storybook against packed tarballs",
        "run": "npm run build-storybook:packed",
        "advisory": false,
        "condition": null
      }
    ]
  },
  {
    "id": "figma-plugin",
    "condition": null,
    "steps": [
      {
        "name": "Typecheck, test and build",
        "run": "npm run figma-plugin:typecheck && npm run figma-plugin:test && npm run figma-plugin:build",
        "advisory": false,
        "condition": null
      }
    ]
  }
] as const;
