// Generated by npm run contracts:generate. Do not edit.
import type { ComponentMetadata } from '@solidaris/contracts';
import { AccordionMetadata as m0 } from '../lib/accordion/accordion.metadata';
import { CopyableTextMetadata as m1 } from '../lib/copyable-text/copyable-text.metadata';
import { DelayPredictionCardMetadata as m2 } from '../lib/delay-prediction-card/delay-prediction-card.metadata';
import { DetailListMetadata as m3 } from '../lib/detail-list/detail-list.metadata';
import { DrawerMetadata as m4 } from '../lib/drawer/drawer.metadata';
import { EmptyStateMetadata as m5 } from '../lib/empty-state/empty-state.metadata';
import { FormFieldMetadata as m6 } from '../lib/form-field/form-field.metadata';
import { IconMetadata as m7 } from '../lib/icon/icon.metadata';
import { InputClearMetadata as m8 } from '../lib/input-clear/input-clear.metadata';
import { ListMetadata as m9 } from '../lib/list/list.metadata';
import { NavShellMetadata as m10 } from '../lib/nav-shell/nav-shell.metadata';
import { PlectrumAvatarMetadata as m11 } from '../lib/plectrum-avatar/plectrum-avatar.metadata';
import { ProfileCardMetadata as m12 } from '../lib/profile-card/profile-card.metadata';
import { ProfileDrawerMetadata as m13 } from '../lib/profile-drawer/profile-drawer.metadata';
import { SkeletonSlotMetadata as m14 } from '../lib/skeleton-slot/skeleton-slot.metadata';
import { SubNavShellMetadata as m15 } from '../lib/sub-nav-shell/sub-nav-shell.metadata';
import { TimelineMetadata as m16 } from '../lib/timeline/timeline.metadata';
import { ToolbarMetadata as m17 } from '../lib/toolbar/toolbar.metadata';
import { TopNavMetadata as m18 } from '../lib/top-nav/top-nav.metadata';
import { TransactionsCicsModalMetadata as m19 } from '../lib/transactions-cics-modal/transactions-cics-modal.metadata';
export const COMPONENT_METADATA_GLOB = 'libs/ui/src/lib/**/*.metadata.ts';
export const ALL_COMPONENT_METADATA: readonly ComponentMetadata[] = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19];
export const COMPONENT_SOURCES: Readonly<Record<string, { metadata: string; docs: string }>> = {
  "plectrum:accordion": {
    "metadata": "libs/ui/src/lib/accordion/accordion.metadata.ts",
    "docs": "libs/ui/src/lib/accordion/accordion.mdx"
  },
  "plectrum:copyable-text": {
    "metadata": "libs/ui/src/lib/copyable-text/copyable-text.metadata.ts",
    "docs": "libs/ui/src/lib/copyable-text/copyable-text.mdx"
  },
  "plectrum:delay-prediction-card": {
    "metadata": "libs/ui/src/lib/delay-prediction-card/delay-prediction-card.metadata.ts",
    "docs": "libs/ui/src/lib/delay-prediction-card/delay-prediction-card.mdx"
  },
  "plectrum:detail-list": {
    "metadata": "libs/ui/src/lib/detail-list/detail-list.metadata.ts",
    "docs": "libs/ui/src/lib/detail-list/detail-list.mdx"
  },
  "plectrum:drawer": {
    "metadata": "libs/ui/src/lib/drawer/drawer.metadata.ts",
    "docs": "libs/ui/src/lib/drawer/drawer.mdx"
  },
  "plectrum:empty-state": {
    "metadata": "libs/ui/src/lib/empty-state/empty-state.metadata.ts",
    "docs": "libs/ui/src/lib/empty-state/empty-state.mdx"
  },
  "plectrum:form-field": {
    "metadata": "libs/ui/src/lib/form-field/form-field.metadata.ts",
    "docs": "libs/ui/src/lib/form-field/form-field.mdx"
  },
  "plectrum:icon": {
    "metadata": "libs/ui/src/lib/icon/icon.metadata.ts",
    "docs": "libs/ui/src/lib/icon/icon.mdx"
  },
  "plectrum:input-clear": {
    "metadata": "libs/ui/src/lib/input-clear/input-clear.metadata.ts",
    "docs": "libs/ui/src/lib/input-clear/input-clear.mdx"
  },
  "plectrum:list": {
    "metadata": "libs/ui/src/lib/list/list.metadata.ts",
    "docs": "libs/ui/src/lib/list/list.mdx"
  },
  "plectrum:nav-shell": {
    "metadata": "libs/ui/src/lib/nav-shell/nav-shell.metadata.ts",
    "docs": "libs/ui/src/lib/nav-shell/nav-shell.mdx"
  },
  "plectrum:plectrum-avatar": {
    "metadata": "libs/ui/src/lib/plectrum-avatar/plectrum-avatar.metadata.ts",
    "docs": "libs/ui/src/lib/plectrum-avatar/plectrum-avatar.mdx"
  },
  "plectrum:profile-card": {
    "metadata": "libs/ui/src/lib/profile-card/profile-card.metadata.ts",
    "docs": "libs/ui/src/lib/profile-card/profile-card.mdx"
  },
  "plectrum:profile-drawer": {
    "metadata": "libs/ui/src/lib/profile-drawer/profile-drawer.metadata.ts",
    "docs": "libs/ui/src/lib/profile-drawer/profile-drawer.mdx"
  },
  "plectrum:skeleton-slot": {
    "metadata": "libs/ui/src/lib/skeleton-slot/skeleton-slot.metadata.ts",
    "docs": "libs/ui/src/lib/skeleton-slot/skeleton-slot.mdx"
  },
  "plectrum:sub-nav-shell": {
    "metadata": "libs/ui/src/lib/sub-nav-shell/sub-nav-shell.metadata.ts",
    "docs": "libs/ui/src/lib/sub-nav-shell/sub-nav-shell.mdx"
  },
  "plectrum:timeline": {
    "metadata": "libs/ui/src/lib/timeline/timeline.metadata.ts",
    "docs": "libs/ui/src/lib/timeline/timeline.mdx"
  },
  "plectrum:toolbar": {
    "metadata": "libs/ui/src/lib/toolbar/toolbar.metadata.ts",
    "docs": "libs/ui/src/lib/toolbar/toolbar.mdx"
  },
  "plectrum:top-nav": {
    "metadata": "libs/ui/src/lib/top-nav/top-nav.metadata.ts",
    "docs": "libs/ui/src/lib/top-nav/top-nav.mdx"
  },
  "plectrum:transactions-cics-modal": {
    "metadata": "libs/ui/src/lib/transactions-cics-modal/transactions-cics-modal.metadata.ts",
    "docs": "libs/ui/src/lib/transactions-cics-modal/transactions-cics-modal.mdx"
  }
};
