// =============================================================================
// libs/ui/src/storybook/docs-component-index.component.ts
// Living component index (Docs/Component status). Data: .ai/contracts/index.json,
// regenerated by `npm run generate-index` and CI-gated.
//
// PrimeNG components used:
//   - pds-toolbar — search + status filter in start, visible / total in end
//   - p-table — one row per component, sortable
//   - p-iconfield + pInputText — search name, BEM block, owner, dependants
//   - p-selectButton — filter by governance status (≤ 5 options); count is a p-badge
//   - p-tag — status (same severities as pds-docs-status) and owner (secondary)
//   - p-badge — per-status count on each filter option, plus visible / total
//   - pds-docs-link — component name → its docs page; badge definitions
//
// Consumer-facing columns only: name (linked), status, owner, used by. The
// index also carries `category` (atomic level) and `primeNg` (the generator's
// lineage hint, e.g. "Api") — internal fields that stay out of this table.
//
// Docs links are resolved at runtime from Storybook's own index.json (the
// docs entry whose importPath sits in the component's folder), so the page
// never hand-copies story ids. When the index cannot be read, names stay text.
//
// Styles: c-docs-component-index* in libs/styles/src/06-components/_components.docs-figures.scss
// (toolbar rhythm, monospace cells — PrimeNG owns the rest). The link-button
// padding bridge lives in 01-settings/_settings.docs-figures.scss.
// =============================================================================

import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  signal,
  ViewEncapsulation,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { ComponentOwner, ComponentStatus } from '@solidaris/contracts';
import { Badge } from 'primeng/badge';
import { IconField } from 'primeng/iconfield';
import { InputIcon } from 'primeng/inputicon';
import { InputText } from 'primeng/inputtext';
import { SelectButton } from 'primeng/selectbutton';
import { TableModule } from 'primeng/table';
import { Tag } from 'primeng/tag';
import { ToolbarComponent } from '../lib/toolbar/toolbar.component';
import { DocsLinkComponent } from './docs-link.component';
import {
  DOCS_STATUS_DEFINITIONS_PATH,
  OWNER_LABEL,
  STATUS_PRESENTATION,
  type StatusSeverity,
} from './docs-status.component';

/** The slice of .ai/contracts/index.json the figure reads. */
export interface ContractsComponentEntry {
  path: string;
  category: string;
  status?: string;
  owner?: string;
  metadata: boolean;
  bemBlock: string | null;
  primeNg: string | null;
  usedBy: readonly string[];
}

export interface ContractsIndex {
  meta: { generated: string };
  components: Readonly<Record<string, ContractsComponentEntry>>;
  summary: { totalComponents: number; componentsWithMetadata: number };
}

/** Storybook's index.json (v5) — the part needed to find a docs page. */
interface StorybookIndex {
  entries: Readonly<
    Record<string, { id: string; type: string; importPath: string }>
  >;
}

type IndexStatus = ComponentStatus | 'undeclared';
type StatusFilter = IndexStatus | 'all';

interface StatusOption {
  label: string;
  count: number;
  value: StatusFilter;
}

const STATUS_ORDER: readonly IndexStatus[] = [
  'core',
  'candidate',
  'app',
  'deprecated',
  'undeclared',
];

const STATUSES: ReadonlySet<string> = new Set<string>(
  Object.keys(STATUS_PRESENTATION),
);
const OWNERS: ReadonlySet<string> = new Set<string>(Object.keys(OWNER_LABEL));

interface ComponentRow {
  name: string;
  status: IndexStatus;
  statusLabel: string;
  statusSeverity: StatusSeverity | 'secondary';
  ownerLabel: string | null;
  bemBlock: string | null;
  usedBy: readonly string[];
  /** Manager route of the component's docs page, when Storybook's index names one. */
  docsPath: string | null;
}

function toStatus(value: string | undefined): IndexStatus {
  return value && STATUSES.has(value)
    ? (value as ComponentStatus)
    : 'undeclared';
}

function toOwnerLabel(value: string | undefined): string | null {
  return value && OWNERS.has(value)
    ? OWNER_LABEL[value as ComponentOwner]
    : null;
}

function statusLabel(status: IndexStatus): string {
  return status === 'undeclared'
    ? 'Undeclared'
    : STATUS_PRESENTATION[status].label;
}

function statusSeverity(status: IndexStatus): StatusSeverity | 'secondary' {
  return status === 'undeclared'
    ? 'secondary'
    : STATUS_PRESENTATION[status].severity;
}

function folderOf(path: string): string {
  return path.replace(/^\.\//, '').replace(/\/[^/]*$/, '');
}

@Component({
  selector: 'pds-docs-component-index',
  imports: [
    FormsModule,
    TableModule,
    Tag,
    Badge,
    IconField,
    InputIcon,
    InputText,
    SelectButton,
    ToolbarComponent,
    DocsLinkComponent,
  ],
  templateUrl: './docs-component-index.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'c-docs-component-index o-layout--block o-layout--margin-block-3',
  },
})
export class DocsComponentIndexComponent {
  readonly index = input.required<ContractsIndex>();
  readonly pageSize = input(25);

  protected readonly definitionsPath = DOCS_STATUS_DEFINITIONS_PATH;

  protected readonly search = signal('');
  protected readonly status = signal<StatusFilter>('all');
  protected readonly first = signal(0);

  /** Component folder → docs page id, from Storybook's index.json. */
  private readonly docsIds = signal<ReadonlyMap<string, string>>(new Map());

  constructor() {
    void this.loadDocsIds();
  }

  protected readonly rows = computed<readonly ComponentRow[]>(() => {
    const docsIds = this.docsIds();
    return Object.entries(this.index().components).map(([name, entry]) => {
      const status = toStatus(entry.status);
      const docsId = docsIds.get(folderOf(entry.path));
      return {
        name,
        status,
        statusLabel: statusLabel(status),
        statusSeverity: statusSeverity(status),
        ownerLabel: toOwnerLabel(entry.owner),
        bemBlock: entry.bemBlock,
        usedBy: entry.usedBy,
        docsPath: docsId ? `/docs/${docsId}` : null,
      };
    });
  });

  protected readonly statusOptions = computed(() => {
    const rows = this.rows();
    const options: StatusOption[] = [
      { label: 'All', count: rows.length, value: 'all' },
    ];
    for (const status of STATUS_ORDER) {
      const count = rows.filter((row) => row.status === status).length;
      if (count > 0) {
        options.push({ label: statusLabel(status), count, value: status });
      }
    }
    return options;
  });

  protected readonly visible = computed(() => {
    const status = this.status();
    const needle = this.search().trim().toLowerCase();
    return this.rows().filter((row) => {
      if (status !== 'all' && row.status !== status) return false;
      if (!needle) return true;
      return [
        row.name,
        row.bemBlock,
        row.ownerLabel,
        row.statusLabel,
        ...row.usedBy,
      ].some((field) => field?.toLowerCase().includes(needle));
    });
  });

  /** Generation time of the index, in UTC so every reader sees the same text. */
  protected readonly generated = computed(() => {
    const date = new Date(this.index().meta.generated);
    if (Number.isNaN(date.getTime())) return this.index().meta.generated;
    return `${date.toLocaleString('en-GB', {
      dateStyle: 'medium',
      timeStyle: 'short',
      timeZone: 'UTC',
    })} UTC`;
  });

  protected onSearch(value: string): void {
    this.search.set(value);
    this.first.set(0);
  }

  protected onStatus(value: StatusFilter): void {
    this.status.set(value);
    this.first.set(0);
  }

  private async loadDocsIds(): Promise<void> {
    if (typeof fetch !== 'function') return;
    try {
      // Relative to iframe.html, so it resolves in dev and in a static build under a sub-path.
      const response = await fetch('./index.json');
      if (!response.ok) return;
      const storybook = (await response.json()) as StorybookIndex;
      const byFolder = new Map<string, string>();
      for (const entry of Object.values(storybook.entries ?? {})) {
        if (entry.type !== 'docs') continue;
        const folder = folderOf(entry.importPath);
        if (!byFolder.has(folder)) byFolder.set(folder, entry.id);
      }
      this.docsIds.set(byFolder);
    } catch {
      // Index unavailable — component names stay plain text.
    }
  }
}
