// AUTO-GENERATED by `npm run tokens:report` (tokens-sync.yml) — do not edit.
// Record of the last promoted Figma → repository token sync: what changed,
// which checks ran, and the outcome. Values are the before/after of that sync,
// not a token reference — current values are read from the CSSOM
// (.ai/rules/10-css-ssot.md). Rendered by Docs/Token pipeline/Sync status.
import type { SyncReport } from './sync-report.types';

export const SYNC_REPORT: SyncReport = {
  "generatedAt": "2026-09-07T02:25:44.410Z",
  "source": null,
  "branch": "design-tokens/sync",
  "sha": "d702032",
  "actor": null,
  "runNumber": null,
  "runUrl": null,
  "sets": [
    "Component Color Scheme/Light",
    "Primitive/Mode 1",
    "Semantic Color Scheme/Light",
    "App/Mode 1",
    "Semantic Common/Mode 1",
    "Component Common/Mode 1",
    "Custom/Mode 1"
  ],
  "leafCount": 3499,
  "resolvedCount": 3385,
  "unresolved": 114,
  "outcomes": {},
  "diff": {
    "base": {
      "available": true,
      "label": "HEAD:libs/plectrum/src/tokens.json"
    },
    "changed": [],
    "reordered": [],
    "added": [],
    "removed": []
  },
  "checks": [
    {
      "id": "integrity",
      "name": "Value integrity",
      "status": "WARN",
      "detail": "114 unresolved aliases. Check the variables in Figma.",
      "items": [
        "surface.0 → {extremes.white} (missing)",
        "button.secondary.background → {surface.0} (unresolved)",
        "button.danger.active.color → {surface.0} (unresolved)",
        "button.contrast.hover.color → {surface.0} (unresolved)",
        "button.contrast.active.color → {surface.0} (unresolved)",
        "button.contrast.color → {surface.0} (unresolved)",
        "toggleswitch.handle.hover.background → {surface.0} (unresolved)",
        "toggleswitch.handle.checked.background → {surface.0} (unresolved)",
        "toggleswitch.handle.checked.hover.background → {surface.0} (unresolved)",
        "form.field.background → {surface.0} (unresolved)",
        "autocomplete.dropdown.background → {form.field.background} (unresolved)",
        "badge.contrast.color → {button.contrast.color} (unresolved)",
        "tag.contrast.color → {surface.0} (unresolved)",
        "datepicker.dropdown.background → {form.field.background} (unresolved)",
        "datepicker.today.color → {surface.0} (unresolved)",
        "colorpicker.handle.color → {surface.0} (unresolved)",
        "slider.handle.content.background → {surface.0} (unresolved)",
        "togglebutton.content.checked.background → {surface.0} (unresolved)",
        "tooltip.color → {surface.0} (unresolved)",
        "toast.contrast.detail.color → {surface.0} (unresolved)"
      ]
    },
    {
      "id": "build",
      "name": "Build",
      "status": "NOT RUN",
      "detail": "Not run.",
      "items": []
    },
    {
      "id": "audit",
      "name": "Drift audit",
      "status": "NOT RUN",
      "detail": "Not run.",
      "items": []
    },
    {
      "id": "coverage",
      "name": "Preset coverage",
      "status": "NOT RUN",
      "detail": "Not run.",
      "items": []
    },
    {
      "id": "theme",
      "name": "Theme",
      "status": "SKIP",
      "detail": "No theme files in this sync — the plugin has no Theme Designer key yet. Plectrum_v1/ is unchanged.",
      "items": []
    }
  ],
  "result": "preview",
  "resultText": "Preview — run from tokens-sync.yml to include check outcomes and the promotion status."
};
