// AUTO-GENERATED by `npm run tokens:report` (tokens-sync.yml) — do not edit.
// Record of the last promoted Figma → repository token sync: what changed,
// which checks ran, and the outcome. Values are the before/after of that sync,
// not a token reference — current values are read from the CSSOM
// (.ai/rules/10-css-ssot.md). Rendered by Docs/Token pipeline/Sync status.
import type { SyncReport } from './sync-report.types';

export const SYNC_REPORT: SyncReport = {
  "generatedAt": "2026-09-07T11:49:43.674Z",
  "source": "primeui-figma-plugin-v4",
  "branch": "design-tokens/sync",
  "sha": "9eccdc3",
  "actor": "solidaris-danielbodigil",
  "runNumber": "10",
  "runUrl": "https://github.com/solidaris-danielbodigil/solidaris-plectrum/actions/runs/34118572239",
  "sets": [
    "aura/component/light",
    "aura/primitive",
    "aura/semantic/light",
    "aura/app",
    "aura/custom",
    "aura/semantic/common",
    "aura/component/common",
    "aura/effects"
  ],
  "leafCount": 2677,
  "resolvedCount": 2677,
  "unresolved": 0,
  "outcomes": {
    "build": "success",
    "audit": "success",
    "validate": "success",
    "theme": "success"
  },
  "diff": {
    "base": {
      "available": true,
      "label": "origin/main:libs/plectrum/src/tokens.json"
    },
    "changed": [],
    "reordered": [],
    "added": [],
    "removed": []
  },
  "checks": [
    {
      "id": "integrity",
      "name": "Value integrity",
      "status": "PASS",
      "detail": "Every alias resolves to a literal.",
      "items": []
    },
    {
      "id": "build",
      "name": "Build",
      "status": "OK",
      "detail": "Generated SCSS and the Storybook token manifest were refreshed from this dump.",
      "items": []
    },
    {
      "id": "audit",
      "name": "Drift audit",
      "status": "PASS",
      "detail": "Figma, the PrimeNG preset and the generated SCSS agree.",
      "items": []
    },
    {
      "id": "coverage",
      "name": "Preset coverage",
      "status": "WARN",
      "detail": "12 code-owned gaps (allowlisted: spacing, durations, focus style). Expected.",
      "items": [
        "focus.ring.style",
        "form.field.focus.ring.style",
        "form.field.transition.duration",
        "list.header.padding",
        "list.option.group.padding",
        "list.option.padding",
        "list.padding",
        "megamenu.horizontal.orientation.padding",
        "navigation.item.padding",
        "navigation.list.padding",
        "navigation.submenu.label.padding",
        "transition.duration",
        "Allowlist entries that now resolve and can be removed: accordion.panel.border.width.bottom, button.contrast.color, button.contrast.hover.color, content.background, emutnav.item.active.color, form.field.background, megamenu.item.active.color, menubar.item.active.color, overlay.modal.background, overlay.popover.background, overlay.select.background, stepper.step.number.active.color, surface.0, tabs.tablist.border.width.bottom"
      ]
    },
    {
      "id": "theme",
      "name": "Theme",
      "status": "SKIP",
      "detail": "No theme files in this sync — the plugin has no Theme Designer key yet. Plectrum_v1/ is unchanged.",
      "items": []
    }
  ],
  "result": "promote",
  "resultText": "A promotion pull request is opened for developer review. Nothing changes in the published packages until it is merged."
};
