// AUTO-GENERATED by `npm run tokens:build` — do not edit.
// Source: libs/plectrum/src/tokens.json + tools/tokens/alias-map.json
export interface TokenAnnotation {
  cssVar: string;
  category: string;
  group: string;
  /** Figma variable path, when the token originates from tokens.json. */
  figmaRef: string | null;
}

/**
 * Annotations for tokens sourced from Figma. Values are NOT here by design —
 * read them from the CSSOM. Tokens absent from this list still render, grouped
 * by convention (see token-taxonomy.ts).
 */
export const TOKEN_ANNOTATIONS: TokenAnnotation[] = [
  {
    "cssVar": "--pds-color-blue-100",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/100"
  },
  {
    "cssVar": "--pds-color-blue-200",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/200"
  },
  {
    "cssVar": "--pds-color-blue-300",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/300"
  },
  {
    "cssVar": "--pds-color-blue-400",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/400"
  },
  {
    "cssVar": "--pds-color-blue-50",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/50"
  },
  {
    "cssVar": "--pds-color-blue-500",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/500"
  },
  {
    "cssVar": "--pds-color-blue-600",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/600"
  },
  {
    "cssVar": "--pds-color-blue-700",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/700"
  },
  {
    "cssVar": "--pds-color-blue-800",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/800"
  },
  {
    "cssVar": "--pds-color-blue-900",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/900"
  },
  {
    "cssVar": "--pds-color-blue-950",
    "category": "color",
    "group": "blue",
    "figmaRef": "blue/950"
  },
  {
    "cssVar": "--pds-color-brand",
    "category": "color",
    "group": "brand",
    "figmaRef": "brand"
  },
  {
    "cssVar": "--pds-color-brand-active",
    "category": "color",
    "group": "brand",
    "figmaRef": "brand"
  },
  {
    "cssVar": "--pds-color-brand-hover",
    "category": "color",
    "group": "brand",
    "figmaRef": "brand"
  },
  {
    "cssVar": "--pds-color-brand-subtle",
    "category": "color",
    "group": "brand",
    "figmaRef": "brand"
  },
  {
    "cssVar": "--pds-color-card-border",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-content",
    "category": "color",
    "group": "content",
    "figmaRef": "content"
  },
  {
    "cssVar": "--pds-color-content-bg",
    "category": "color",
    "group": "content",
    "figmaRef": "content"
  },
  {
    "cssVar": "--pds-color-content-border",
    "category": "color",
    "group": "content",
    "figmaRef": "content"
  },
  {
    "cssVar": "--pds-color-content-hover",
    "category": "color",
    "group": "content",
    "figmaRef": "content"
  },
  {
    "cssVar": "--pds-color-content-hover-bg",
    "category": "color",
    "group": "content",
    "figmaRef": "content"
  },
  {
    "cssVar": "--pds-color-danger",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-danger-emphasis",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-danger-subtle",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-divider",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-error",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-focus",
    "category": "color",
    "group": "focus",
    "figmaRef": "focus"
  },
  {
    "cssVar": "--pds-color-form-bg",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-border",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-border-focus",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-border-hover",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-border-invalid",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-disabled-bg",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-disabled-text",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-filled-bg",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-float-label",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-float-label-active",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-float-label-focus",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-float-label-invalid",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-icon",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-invalid-placeholder",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-placeholder",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-form-text",
    "category": "color",
    "group": "form",
    "figmaRef": "form"
  },
  {
    "cssVar": "--pds-color-gray-100",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/100"
  },
  {
    "cssVar": "--pds-color-gray-200",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/200"
  },
  {
    "cssVar": "--pds-color-gray-300",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/300"
  },
  {
    "cssVar": "--pds-color-gray-400",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/400"
  },
  {
    "cssVar": "--pds-color-gray-50",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/50"
  },
  {
    "cssVar": "--pds-color-gray-500",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/500"
  },
  {
    "cssVar": "--pds-color-gray-600",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/600"
  },
  {
    "cssVar": "--pds-color-gray-700",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/700"
  },
  {
    "cssVar": "--pds-color-gray-800",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/800"
  },
  {
    "cssVar": "--pds-color-gray-900",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/900"
  },
  {
    "cssVar": "--pds-color-gray-950",
    "category": "color",
    "group": "gray",
    "figmaRef": "gray/950"
  },
  {
    "cssVar": "--pds-color-green-100",
    "category": "color",
    "group": "green",
    "figmaRef": "green/100"
  },
  {
    "cssVar": "--pds-color-green-200",
    "category": "color",
    "group": "green",
    "figmaRef": "green/200"
  },
  {
    "cssVar": "--pds-color-green-300",
    "category": "color",
    "group": "green",
    "figmaRef": "green/300"
  },
  {
    "cssVar": "--pds-color-green-400",
    "category": "color",
    "group": "green",
    "figmaRef": "green/400"
  },
  {
    "cssVar": "--pds-color-green-50",
    "category": "color",
    "group": "green",
    "figmaRef": "green/50"
  },
  {
    "cssVar": "--pds-color-green-500",
    "category": "color",
    "group": "green",
    "figmaRef": "green/500"
  },
  {
    "cssVar": "--pds-color-green-600",
    "category": "color",
    "group": "green",
    "figmaRef": "green/600"
  },
  {
    "cssVar": "--pds-color-green-700",
    "category": "color",
    "group": "green",
    "figmaRef": "green/700"
  },
  {
    "cssVar": "--pds-color-green-800",
    "category": "color",
    "group": "green",
    "figmaRef": "green/800"
  },
  {
    "cssVar": "--pds-color-green-900",
    "category": "color",
    "group": "green",
    "figmaRef": "green/900"
  },
  {
    "cssVar": "--pds-color-green-950",
    "category": "color",
    "group": "green",
    "figmaRef": "green/950"
  },
  {
    "cssVar": "--pds-color-highlight",
    "category": "color",
    "group": "highlight",
    "figmaRef": "highlight"
  },
  {
    "cssVar": "--pds-color-highlight-focus",
    "category": "color",
    "group": "highlight",
    "figmaRef": "highlight"
  },
  {
    "cssVar": "--pds-color-highlight-focus-text",
    "category": "color",
    "group": "highlight",
    "figmaRef": "highlight"
  },
  {
    "cssVar": "--pds-color-highlight-text",
    "category": "color",
    "group": "highlight",
    "figmaRef": "highlight"
  },
  {
    "cssVar": "--pds-color-info",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-info-subtle",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-mask",
    "category": "color",
    "group": "mask",
    "figmaRef": "mask"
  },
  {
    "cssVar": "--pds-color-mask-bg",
    "category": "color",
    "group": "mask",
    "figmaRef": "mask"
  },
  {
    "cssVar": "--pds-color-nav-item",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-item-active",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-item-active-bg",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-item-focus",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-item-focus-bg",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-item-icon",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-item-icon-active",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-item-icon-focus",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-submenu-icon",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-nav-submenu-label",
    "category": "color",
    "group": "navigation",
    "figmaRef": "navigation"
  },
  {
    "cssVar": "--pds-color-neutral-100",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/100"
  },
  {
    "cssVar": "--pds-color-neutral-200",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/200"
  },
  {
    "cssVar": "--pds-color-neutral-300",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/300"
  },
  {
    "cssVar": "--pds-color-neutral-400",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/400"
  },
  {
    "cssVar": "--pds-color-neutral-50",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/50"
  },
  {
    "cssVar": "--pds-color-neutral-500",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/500"
  },
  {
    "cssVar": "--pds-color-neutral-600",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/600"
  },
  {
    "cssVar": "--pds-color-neutral-700",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/700"
  },
  {
    "cssVar": "--pds-color-neutral-800",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/800"
  },
  {
    "cssVar": "--pds-color-neutral-900",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/900"
  },
  {
    "cssVar": "--pds-color-neutral-950",
    "category": "color",
    "group": "neutral",
    "figmaRef": "neutral/950"
  },
  {
    "cssVar": "--pds-color-orange-100",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/100"
  },
  {
    "cssVar": "--pds-color-orange-200",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/200"
  },
  {
    "cssVar": "--pds-color-orange-300",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/300"
  },
  {
    "cssVar": "--pds-color-orange-400",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/400"
  },
  {
    "cssVar": "--pds-color-orange-50",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/50"
  },
  {
    "cssVar": "--pds-color-orange-500",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/500"
  },
  {
    "cssVar": "--pds-color-orange-600",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/600"
  },
  {
    "cssVar": "--pds-color-orange-700",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/700"
  },
  {
    "cssVar": "--pds-color-orange-800",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/800"
  },
  {
    "cssVar": "--pds-color-orange-900",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/900"
  },
  {
    "cssVar": "--pds-color-orange-950",
    "category": "color",
    "group": "orange",
    "figmaRef": "orange/950"
  },
  {
    "cssVar": "--pds-color-overlay-modal-border",
    "category": "color",
    "group": "overlay",
    "figmaRef": "overlay"
  },
  {
    "cssVar": "--pds-color-overlay-popover-border",
    "category": "color",
    "group": "overlay",
    "figmaRef": "overlay"
  },
  {
    "cssVar": "--pds-color-overlay-select-border",
    "category": "color",
    "group": "overlay",
    "figmaRef": "overlay"
  },
  {
    "cssVar": "--pds-color-panel-border",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-primary-100",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/100"
  },
  {
    "cssVar": "--pds-color-primary-200",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/200"
  },
  {
    "cssVar": "--pds-color-primary-300",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/300"
  },
  {
    "cssVar": "--pds-color-primary-400",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/400"
  },
  {
    "cssVar": "--pds-color-primary-50",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/50"
  },
  {
    "cssVar": "--pds-color-primary-500",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/500"
  },
  {
    "cssVar": "--pds-color-primary-600",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/600"
  },
  {
    "cssVar": "--pds-color-primary-700",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/700"
  },
  {
    "cssVar": "--pds-color-primary-800",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/800"
  },
  {
    "cssVar": "--pds-color-primary-900",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/900"
  },
  {
    "cssVar": "--pds-color-primary-950",
    "category": "color",
    "group": "primary",
    "figmaRef": "primary/950"
  },
  {
    "cssVar": "--pds-color-primary-interactive",
    "category": "color",
    "group": "primary-interactive",
    "figmaRef": "primary-interactive"
  },
  {
    "cssVar": "--pds-color-primary-interactive-active",
    "category": "color",
    "group": "primary-interactive",
    "figmaRef": "primary-interactive"
  },
  {
    "cssVar": "--pds-color-primary-interactive-contrast",
    "category": "color",
    "group": "primary-interactive",
    "figmaRef": "primary-interactive"
  },
  {
    "cssVar": "--pds-color-primary-interactive-hover",
    "category": "color",
    "group": "primary-interactive",
    "figmaRef": "primary-interactive"
  },
  {
    "cssVar": "--pds-color-red-100",
    "category": "color",
    "group": "red",
    "figmaRef": "red/100"
  },
  {
    "cssVar": "--pds-color-red-200",
    "category": "color",
    "group": "red",
    "figmaRef": "red/200"
  },
  {
    "cssVar": "--pds-color-red-300",
    "category": "color",
    "group": "red",
    "figmaRef": "red/300"
  },
  {
    "cssVar": "--pds-color-red-400",
    "category": "color",
    "group": "red",
    "figmaRef": "red/400"
  },
  {
    "cssVar": "--pds-color-red-50",
    "category": "color",
    "group": "red",
    "figmaRef": "red/50"
  },
  {
    "cssVar": "--pds-color-red-500",
    "category": "color",
    "group": "red",
    "figmaRef": "red/500"
  },
  {
    "cssVar": "--pds-color-red-600",
    "category": "color",
    "group": "red",
    "figmaRef": "red/600"
  },
  {
    "cssVar": "--pds-color-red-700",
    "category": "color",
    "group": "red",
    "figmaRef": "red/700"
  },
  {
    "cssVar": "--pds-color-red-800",
    "category": "color",
    "group": "red",
    "figmaRef": "red/800"
  },
  {
    "cssVar": "--pds-color-red-900",
    "category": "color",
    "group": "red",
    "figmaRef": "red/900"
  },
  {
    "cssVar": "--pds-color-red-950",
    "category": "color",
    "group": "red",
    "figmaRef": "red/950"
  },
  {
    "cssVar": "--pds-color-rose-100",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/100"
  },
  {
    "cssVar": "--pds-color-rose-200",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/200"
  },
  {
    "cssVar": "--pds-color-rose-300",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/300"
  },
  {
    "cssVar": "--pds-color-rose-400",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/400"
  },
  {
    "cssVar": "--pds-color-rose-50",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/50"
  },
  {
    "cssVar": "--pds-color-rose-500",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/500"
  },
  {
    "cssVar": "--pds-color-rose-600",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/600"
  },
  {
    "cssVar": "--pds-color-rose-700",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/700"
  },
  {
    "cssVar": "--pds-color-rose-800",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/800"
  },
  {
    "cssVar": "--pds-color-rose-900",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/900"
  },
  {
    "cssVar": "--pds-color-rose-950",
    "category": "color",
    "group": "rose",
    "figmaRef": "rose/950"
  },
  {
    "cssVar": "--pds-color-solidaris-red-500",
    "category": "color",
    "group": "solidaris",
    "figmaRef": "basic/solidaris/500"
  },
  {
    "cssVar": "--pds-color-success",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-success-subtle",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-surface",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-surface-0",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/0"
  },
  {
    "cssVar": "--pds-color-surface-100",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/100"
  },
  {
    "cssVar": "--pds-color-surface-200",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/200"
  },
  {
    "cssVar": "--pds-color-surface-300",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/300"
  },
  {
    "cssVar": "--pds-color-surface-400",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/400"
  },
  {
    "cssVar": "--pds-color-surface-50",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/50"
  },
  {
    "cssVar": "--pds-color-surface-500",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/500"
  },
  {
    "cssVar": "--pds-color-surface-600",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/600"
  },
  {
    "cssVar": "--pds-color-surface-700",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/700"
  },
  {
    "cssVar": "--pds-color-surface-800",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/800"
  },
  {
    "cssVar": "--pds-color-surface-900",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/900"
  },
  {
    "cssVar": "--pds-color-surface-950",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface/950"
  },
  {
    "cssVar": "--pds-color-surface-border",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-surface-default",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-surface-muted",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-surface-subtle",
    "category": "color",
    "group": "surface",
    "figmaRef": "surface"
  },
  {
    "cssVar": "--pds-color-text",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-text-hover",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-text-inverse",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-text-link",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-text-link-hover",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-text-link-visited",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-text-muted",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-text-muted-hover",
    "category": "color",
    "group": "text",
    "figmaRef": "text"
  },
  {
    "cssVar": "--pds-color-warning",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-warning-subtle",
    "category": "color",
    "group": "feedback",
    "figmaRef": "feedback"
  },
  {
    "cssVar": "--pds-color-yellow-100",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/100"
  },
  {
    "cssVar": "--pds-color-yellow-200",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/200"
  },
  {
    "cssVar": "--pds-color-yellow-300",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/300"
  },
  {
    "cssVar": "--pds-color-yellow-400",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/400"
  },
  {
    "cssVar": "--pds-color-yellow-50",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/50"
  },
  {
    "cssVar": "--pds-color-yellow-500",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/500"
  },
  {
    "cssVar": "--pds-color-yellow-600",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/600"
  },
  {
    "cssVar": "--pds-color-yellow-700",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/700"
  },
  {
    "cssVar": "--pds-color-yellow-800",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/800"
  },
  {
    "cssVar": "--pds-color-yellow-900",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/900"
  },
  {
    "cssVar": "--pds-color-yellow-950",
    "category": "color",
    "group": "yellow",
    "figmaRef": "yellow/950"
  },
  {
    "cssVar": "--pds-focus-ring-color",
    "category": "focus",
    "group": "ring",
    "figmaRef": "focus/ring/color"
  },
  {
    "cssVar": "--pds-focus-ring-offset",
    "category": "focus",
    "group": "ring",
    "figmaRef": "focus/ring/offset"
  },
  {
    "cssVar": "--pds-focus-ring-shadow",
    "category": "focus",
    "group": "ring",
    "figmaRef": null
  },
  {
    "cssVar": "--pds-focus-ring-style",
    "category": "focus",
    "group": "ring",
    "figmaRef": null
  },
  {
    "cssVar": "--pds-focus-ring-width",
    "category": "focus",
    "group": "ring",
    "figmaRef": "focus/ring/width"
  },
  {
    "cssVar": "--pds-radius-lg",
    "category": "radius",
    "group": "radius",
    "figmaRef": "border/radius/lg"
  },
  {
    "cssVar": "--pds-radius-md",
    "category": "radius",
    "group": "radius",
    "figmaRef": "border/radius/md"
  },
  {
    "cssVar": "--pds-radius-none",
    "category": "radius",
    "group": "radius",
    "figmaRef": "border/radius/none"
  },
  {
    "cssVar": "--pds-radius-sm",
    "category": "radius",
    "group": "radius",
    "figmaRef": "border/radius/sm"
  },
  {
    "cssVar": "--pds-radius-xl",
    "category": "radius",
    "group": "radius",
    "figmaRef": "border/radius/xl"
  },
  {
    "cssVar": "--pds-radius-xs",
    "category": "radius",
    "group": "radius",
    "figmaRef": "border/radius/xs"
  },
  {
    "cssVar": "--pds-shadow-form-field",
    "category": "shadow",
    "group": "form",
    "figmaRef": "form/field/shadow"
  },
  {
    "cssVar": "--pds-shadow-overlay-modal",
    "category": "shadow",
    "group": "overlay",
    "figmaRef": "overlay/modal/shadow"
  },
  {
    "cssVar": "--pds-shadow-overlay-navigation",
    "category": "shadow",
    "group": "overlay",
    "figmaRef": "overlay/navigation/shadow"
  },
  {
    "cssVar": "--pds-shadow-overlay-popover",
    "category": "shadow",
    "group": "overlay",
    "figmaRef": "overlay/popover/shadow"
  },
  {
    "cssVar": "--pds-shadow-overlay-select",
    "category": "shadow",
    "group": "overlay",
    "figmaRef": "overlay/select/shadow"
  },
  {
    "cssVar": "--pds-transition-duration",
    "category": "motion",
    "group": "duration",
    "figmaRef": null
  },
  {
    "cssVar": "--pds-transition-duration-mask",
    "category": "motion",
    "group": "duration",
    "figmaRef": null
  }
];
