#!/usr/bin/env node
/**
 * Emits libs/ui/src/storybook/changelog.generated.ts from:
 * - CHANGELOG.md files under libs (none until the first version PR)
 * - pending .changeset/*.md as "Unreleased"
 *
 * Run from the workspace root. Wired into storybook / build-storybook.
 * CI gates the generated file the same way as tokens.generated.ts.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const outFile = join(root, 'libs/ui/src/storybook/changelog.generated.ts');

const LIBS = ['ui', 'plectrum', 'styles'];

/**
 * @typedef {{ packageName: string; version: string; body: string }} ChangelogEntry
 */

/** @type {ChangelogEntry[]} */
const released = [];

for (const lib of LIBS) {
  const changelogPath = join(root, 'libs', lib, 'CHANGELOG.md');
  if (!existsSync(changelogPath)) {
    continue;
  }

  const source = readFileSync(changelogPath, 'utf8');
  const blocks = source.split(/^## /m).slice(1);

  for (const block of blocks) {
    const [heading, ...rest] = block.split('\n');
    const version = heading.replace(/^\[?([^\]]+)\]?.*/, '$1').trim();
    if (!version || /^unreleased$/i.test(version)) {
      continue;
    }

    released.push({
      packageName: `@solidaris/${lib}`,
      version,
      body: rest.join('\n').trim(),
    });
  }
}

/** @type {string[]} */
const unreleased = [];
const changesetDir = join(root, '.changeset');

if (existsSync(changesetDir)) {
  for (const file of readdirSync(changesetDir).sort()) {
    if (!file.endsWith('.md') || file === 'README.md') {
      continue;
    }

    const source = readFileSync(join(changesetDir, file), 'utf8');
    const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    const body = (match?.[2] ?? source).trim();
    if (body) {
      unreleased.push(body);
    }
  }
}

const banner = `// Generated by tools/scripts/changelog-to-ts.mjs — do not edit by hand.
`;

const contents = `${banner}
export interface ChangelogRelease {
  packageName: string;
  version: string;
  body: string;
}

export const CHANGELOG_UNRELEASED: string[] = ${JSON.stringify(unreleased, null, 2)};

export const CHANGELOG_RELEASES: ChangelogRelease[] = ${JSON.stringify(released, null, 2)};
`;

writeFileSync(outFile, contents);
console.log(
  `Wrote ${outFile} (${released.length} release(s), ${unreleased.length} unreleased changeset(s))`,
);
