#!/usr/bin/env node
/**
 * Emits libs/ui/src/storybook/changelog.generated.ts from:
 * - CHANGELOG.md files under libs (none until the first version PR)
 * - pending .changeset/*.md as "Unreleased"
 *
 * Shapes: libs/ui/src/storybook/changelog.types.ts. A changeset keeps its
 * per-package bumps and summary; a release keeps the entries of its
 * `### Major | Minor | Patch Changes` sections.
 *
 * Run from the workspace root. Wired into storybook / build-storybook.
 * CI gates the generated file the same way as tokens.generated.ts.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const outFile = join(root, 'libs/ui/src/storybook/changelog.generated.ts');

const LIBS = ['ui', 'plectrum', 'styles'];
const BUMPS = ['major', 'minor', 'patch'];

/**
 * @typedef {'major' | 'minor' | 'patch'} Bump
 * @typedef {{ packageName: string; bump: Bump }} PackageBump
 * @typedef {{ id: string; bumps: PackageBump[]; summary: string }} Changeset
 * @typedef {{ bump: Bump; text: string }} Change
 * @typedef {{ packageName: string; version: string; changes: Change[]; notes: string }} Release
 */

/** Files are committed with either line ending; parse them the same way. */
const read = (path) => readFileSync(path, 'utf8').replace(/\r\n?/g, '\n');

/**
 * Markdown bullets of a section: `- text`, continuation lines indented.
 * Anything that is not part of a bullet is returned as `rest`.
 * @param {string} source
 * @returns {{ items: string[]; rest: string }}
 */
function parseBullets(source) {
  /** @type {string[]} */
  const items = [];
  /** @type {string[]} */
  const rest = [];

  for (const line of source.split('\n')) {
    const bullet = line.match(/^[-*]\s+(.*)$/);
    if (bullet) {
      items.push(bullet[1].trim());
    } else if (items.length && /^\s+\S/.test(line)) {
      items[items.length - 1] += ` ${line.trim()}`;
    } else if (line.trim()) {
      rest.push(line);
    }
  }

  return { items, rest: rest.join('\n').trim() };
}

/**
 * One `## version` block of a changesets CHANGELOG.md.
 * @param {string} packageName
 * @param {string} version
 * @param {string} body
 * @returns {Release}
 */
function parseRelease(packageName, version, body) {
  /** @type {Change[]} */
  const changes = [];
  /** @type {string[]} */
  const notes = [];

  // `### Major Changes` … split on the section heading, keep the heading text.
  const sections = body.split(/^###\s+/m);
  const preamble = sections.shift() ?? '';
  if (preamble.trim()) notes.push(preamble.trim());

  for (const section of sections) {
    const [heading, ...lines] = section.split('\n');
    const bump = heading.trim().toLowerCase().replace(/\s+changes$/, '');
    const { items, rest } = parseBullets(lines.join('\n'));

    if (BUMPS.includes(bump)) {
      for (const text of items) changes.push({ bump, text });
      if (rest) notes.push(rest);
    } else {
      notes.push(`### ${section.trim()}`);
    }
  }

  return { packageName, version, changes, notes: notes.join('\n\n') };
}

/** @type {Release[]} */
const released = [];

for (const lib of LIBS) {
  const changelogPath = join(root, 'libs', lib, 'CHANGELOG.md');
  if (!existsSync(changelogPath)) {
    continue;
  }

  const blocks = read(changelogPath).split(/^## /m).slice(1);

  for (const block of blocks) {
    const [heading, ...rest] = block.split('\n');
    const version = heading.replace(/^\[?([^\]]+)\]?.*/, '$1').trim();
    if (!version || /^unreleased$/i.test(version)) {
      continue;
    }

    released.push(parseRelease(`@solidaris/${lib}`, version, rest.join('\n').trim()));
  }
}

/** @type {Changeset[]} */
const unreleased = [];
const changesetDir = join(root, '.changeset');

if (existsSync(changesetDir)) {
  for (const file of readdirSync(changesetDir).sort()) {
    if (!file.endsWith('.md') || file === 'README.md') {
      continue;
    }

    const source = read(join(changesetDir, file));
    const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    const summary = (match?.[2] ?? source).trim();
    if (!summary) {
      continue;
    }

    /** @type {PackageBump[]} */
    const bumps = [];
    for (const line of (match?.[1] ?? '').split('\n')) {
      // '@solidaris/ui': major  |  "@solidaris/ui": patch
      const entry = line.match(/^\s*['"]?([^'":\s]+)['"]?\s*:\s*(major|minor|patch)\s*$/);
      if (entry) bumps.push({ packageName: entry[1], bump: entry[2] });
    }

    unreleased.push({ id: file.replace(/\.md$/, ''), bumps, summary });
  }
}

const banner = `// Generated by tools/scripts/changelog-to-ts.mjs — do not edit by hand.
`;

const contents = `${banner}
import type { ChangelogChangeset, ChangelogRelease } from './changelog.types';

export const CHANGELOG_UNRELEASED: ChangelogChangeset[] = ${JSON.stringify(unreleased, null, 2)};

export const CHANGELOG_RELEASES: ChangelogRelease[] = ${JSON.stringify(released, null, 2)};
`;

writeFileSync(outFile, contents);
console.log(
  `Wrote ${outFile} (${released.length} release(s), ${unreleased.length} unreleased changeset(s))`,
);
