import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { checkAdoption } from './records';

export async function generateAdoptionListing(root = process.cwd()): Promise<void> {
  const aggregate = await checkAdoption(root);
  const target = path.join(root, 'libs/ui/src/storybook/adoption-data.generated.ts');
  const body = `// Generated by npm run adoption:generate. Storybook build refreshes this file.\nexport const CENTRAL_ADOPTION: {\n  staleAfterDays: number;\n  usedIn: Readonly<Record<string, readonly { application: string; label: string; kind: 'local-demo' | 'external'; freshness: 'current' | 'stale'; observedAt: string; packageVersion: string }[]>>;\n  missing: readonly { id: string; label: string; kind: 'local-demo' | 'external' }[];\n  reported: readonly { id: string; label: string }[];\n  retired: readonly { id: string; observedAt: string }[];\n} = ${JSON.stringify(aggregate, null, 2)};\n`;
  fs.writeFileSync(target, body);
  console.log(`Storybook adoption listing: ${Object.keys(aggregate.usedIn).length} component(s), ${aggregate.missing.length} application(s) without a report.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateAdoptionListing().catch((error) => { console.error(error); process.exitCode = 1; });
}
