import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readCandidateRecords } from './records';

export function generateCandidateListing(root = process.cwd()): void {
  const records = readCandidateRecords(root);
  const candidates = [...records.submissions.values()]
    .filter((entry) => entry.operation !== 'withdraw' && !records.promotions.has(entry.id))
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((entry) => {
      const review = records.reviews.get(entry.id);
      return { ...entry, reviewState: review?.sourceRevision === entry.origin.revision ? review.decision : 'submitted' };
    });
  const target = path.join(root, 'libs/ui/src/storybook/candidate-data.generated.ts');
  fs.writeFileSync(target, `// Generated by npm run candidate:generate. Storybook build refreshes this file.\nexport const CENTRAL_CANDIDATES = ${JSON.stringify(candidates, null, 2)} as const;\n`);
  console.log(`Storybook candidate listing: ${candidates.length} active record(s).`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) generateCandidateListing();
