/**
 * Style Dictionary 4 config — hybrid --pds-* emitter.
 *
 * Mapped:   --#{$pds-prefix}-color-brand: var(--p-primary-color, <literal>);
 * Unmapped: --#{$pds-prefix}-radius-md: <literal>;
 *
 * The formatter owns the Sass interpolation; SD cannot emit #{$pds-prefix} itself.
 */

import StyleDictionary from 'style-dictionary';

export const GENERATED_BANNER =
  '// AUTO-GENERATED by `npm run tokens:build` — do not edit.\n' +
  '// Source: libs/plectrum/src/tokens.json + tools/tokens/alias-map.json\n';

export function formatHybridScss({ options }) {
  const fileKey = options.fileKey;
  const tokens = (options.computed ?? []).filter((token) => token.file === fileKey);
  const lines = [
    GENERATED_BANNER,
    "@use 'settings.prefix' as *;\n",
    ':root {',
  ];
  for (const token of tokens) {
    lines.push(`  --#{$pds-prefix}-${token.cssName}: ${token.emitted};`);
  }
  lines.push('}\n');
  return `${lines.join('\n')}`;
}

/**
 * Annotations only — never values.
 *
 * Which tokens exist, what they resolve to, the `--p-*` alias and its fallback
 * are all read from the CSSOM at runtime (libs/ui/src/storybook/cssom.ts).
 * This manifest carries the two things a stylesheet cannot express: the Figma
 * node a token came from, and its curated category/group.
 *
 * See .ai/rules/10-css-ssot.md §4.
 */
export function formatManifestTs({ options }) {
  const tokens = options.computed ?? [];
  const payload = tokens
    .map((token) => ({
      cssVar: token.cssVar,
      category: token.category,
      group: token.group,
      figmaRef: token.figmaRef,
    }))
    .sort((a, b) => a.cssVar.localeCompare(b.cssVar));

  return `${GENERATED_BANNER}export interface TokenAnnotation {
  cssVar: string;
  category: string;
  group: string;
  /** Figma variable path, when the token originates from tokens.json. */
  figmaRef: string | null;
}

/**
 * Annotations for tokens sourced from Figma. Values are NOT here by design —
 * read them from the CSSOM. Tokens absent from this list still render, grouped
 * by convention (see token-taxonomy.ts).
 */
export const TOKEN_ANNOTATIONS: TokenAnnotation[] = ${JSON.stringify(payload, null, 2)};
`;
}

export function createStyleDictionary(computed) {
  const tokens = { pds: { generated: { marker: { $value: '1', $type: 'other' } } } };

  return new StyleDictionary({
    tokens,
    hooks: {
      formats: {
        'scss/pds-hybrid': formatHybridScss,
        'ts/pds-manifest': formatManifestTs,
      },
    },
    platforms: {
      scss: {
        buildPath: 'libs/styles/src/01-settings/',
        files: [
          'colors-primitive',
          'colors-semantic',
          'radius',
          'shadows',
          'transitions',
          'focus',
        ].map((fileKey) => ({
          destination: `_settings.${fileKey}.generated.scss`,
          format: 'scss/pds-hybrid',
          options: { fileKey, computed },
        })),
      },
      storybook: {
        buildPath: 'libs/ui/src/storybook/',
        files: [
          {
            destination: 'tokens.generated.ts',
            format: 'ts/pds-manifest',
            options: { computed },
          },
        ],
      },
    },
    log: { verbosity: 'silent' },
  });
}
