import fs from 'node:fs';
import path from 'node:path';
import { z } from 'zod';
import ts from 'typescript';
import { exchangeSchemas } from '../../.ai/contracts/schema/exchange.schema';
import { inventory, filesUnder, posix } from './inventory';
import { readRegistry } from './validate';
import { checkBoundaries } from './boundaries';

const json = (value: unknown) => JSON.stringify(value, null, 2) + '\n';
const generated = '// Generated by npm run contracts:generate. Do not edit.\n';
const entryBarrel = (entry: string) =>
  entry === '.'
    ? 'libs/ui/src/public-api.ts'
    : `libs/ui/src/${entry.slice(2).replaceAll('/', '-')}-api.ts`;
function storyTitle(file: string): string | undefined {
  if (!fs.existsSync(file)) return undefined;
  const ast = ts.createSourceFile(file, fs.readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);
  for (const statement of ast.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || declaration.name.text !== 'meta' || !declaration.initializer || !ts.isObjectLiteralExpression(declaration.initializer)) continue;
      for (const prop of declaration.initializer.properties) {
        if (ts.isPropertyAssignment(prop) && prop.name.getText(ast) === 'title' && ts.isStringLiteral(prop.initializer)) return prop.initializer.text;
      }
    }
  }
  return undefined;
}
export async function generateContracts(
  root = process.cwd(),
  check = false,
): Promise<string[]> {
  const registry = readRegistry(root);
  const items = await inventory(root);
  const config = JSON.parse(
    fs.readFileSync(path.join(root, '.ai/contracts/workspace.json'), 'utf8'),
  );
  const ui = JSON.parse(
    fs.readFileSync(path.join(root, 'libs/ui/package.json'), 'utf8'),
  );
  const styles = JSON.parse(
    fs.readFileSync(path.join(root, 'libs/styles/package.json'), 'utf8'),
  );
  const outputs = new Map<string, string>();
  const coreReviewers = registry.teams.find((team) => team.id === 'design-system');
  const codeOwners = [coreReviewers?.reviewer, ...(coreReviewers?.alternateReviewers ?? [])].filter((owner): owner is string => !!owner);
  if (!codeOwners.length) throw new Error('A Core CODEOWNER must be configured in the team registry.');
  outputs.set('.github/CODEOWNERS', `# Generated from .ai/contracts/registry.json by contracts:generate.\n${['.ai/adoption/', '.ai/candidates/', '.ai/contracts/', 'libs/ui/src/lib/', 'libs/styles/src/01-settings/', 'libs/plectrum/src/tokens.json', 'tools/adoption/', 'tools/candidates/'].map((area) => `${area.padEnd(38)} ${codeOwners.join(' ')}`).join('\n')}\n`);
  const sourceLocations = Object.fromEntries(
    items.map((item) => [
      item.metadata.component.id,
      { metadata: item.metadataPath, docs: item.docsPath },
    ]),
  );
  const imports = items.map(
    (item, i) =>
      `import { ${item.exportSymbol} as m${i} } from '${posix(path.relative('libs/ui/src/storybook', item.metadataPath)).replace(/\.ts$/, '')}';`,
  );
  outputs.set(
    'libs/ui/src/storybook/component-metadata.ts',
    generated +
      `import type { ComponentMetadata } from '@solidaris/contracts';\n` +
      imports.join('\n') +
      `\nexport const COMPONENT_METADATA_GLOB = 'libs/ui/src/lib/**/*.metadata.ts';\nexport const ALL_COMPONENT_METADATA: readonly ComponentMetadata[] = [${items.map((_, i) => `m${i}`).join(', ')}];\nexport const COMPONENT_SOURCES: Readonly<Record<string, { metadata: string; docs: string }>> = ${json(sourceLocations).trim()};\n`,
  );

  const exports = new Map<string, Set<string>>([
    ['.', new Set(config.helperExports.map((p: string) => `./lib/${p}`))],
  ]);
  const symbolIds = new Map<string, string>();
  for (const item of items) {
    const { component, distribution } = item.metadata;
    if (distribution.kind !== 'angular') continue;
    if (symbolIds.has(distribution.exportName))
      throw new Error(`Duplicate Angular export: ${distribution.exportName}`);
    symbolIds.set(distribution.exportName, component.id);
    const entry = distribution.entryPoint;
    const barrel = entryBarrel(entry);
    let importPath = posix(
      path.relative(path.dirname(barrel), path.dirname(item.metadataPath)),
    );
    if (!importPath.startsWith('.')) importPath = './' + importPath;
    const paths = exports.get(entry) ?? new Set<string>();
    paths.add(importPath);
    exports.set(entry, paths);
  }
  for (const [entry, paths] of exports) {
    const folder = entry === '.' ? 'libs/ui/src' : `libs/ui/${entry.slice(2)}`;
    outputs.set(
      entryBarrel(entry),
      generated +
        [...paths]
          .sort()
          .map((p) => `export * from '${p}';`)
          .join('\n') +
        '\n',
    );
    if (entry !== '.')
      outputs.set(
        `${folder}/ng-package.json`,
        json({
          lib: { entryFile: posix(path.relative(folder, entryBarrel(entry))) },
        }),
      );
  }
  outputs.set(
    'libs/ui/src/lib/index.ts',
    generated + `export * from '../public-api';\n`,
  );
  const candidateStyles = items
    .filter((i) => i.metadata.distribution.kind === 'local' && i.metadata.component.scssPath)
    .map((i) => `@use '${posix(path.relative('libs/styles', i.metadata.component.scssPath!))}';`);
  outputs.set('libs/styles/storybook-candidates.scss', generated + candidateStyles.join('\n') + (candidateStyles.length ? '\n' : ''));

  const sourceBlobs = new Map<string, string>();
  for (const app of registry.applications.filter(
    (a) => a.kind === 'local-demo' && a.path,
  )) {
    sourceBlobs.set(
      app.id,
      filesUnder(path.join(root, app.path!))
        .filter(
          (f) => /\.(ts|html)$/.test(f) && !/\.(spec|stories)\.ts$/.test(f),
        )
        .map((f) => fs.readFileSync(f, 'utf8'))
        .join('\n'),
    );
  }
  const usedIn: Record<string, string[]> = {};
  const components: Record<string, unknown> = {};
  const relationships: Record<string, { uses: string[]; usedBy: string[] }> =
    {};
  const byStatus: Record<string, number> = {};
  for (const item of items) {
    const { component, governance, distribution } = item.metadata;
    const source = fs.readFileSync(path.join(root, component.path), 'utf8');
    const selector = /selector:\s*['"]([^'"]+)/.exec(source)?.[1];
    const needles = [
      component.bemBlock,
      selector,
      distribution.kind === 'angular' ? distribution.exportName : undefined,
    ].filter((x): x is string => !!x);
    // Local source observations, not telemetry or proof of runtime adoption.
    usedIn[component.id] = registry.applications
      .filter((app) => {
        const blob = sourceBlobs.get(app.id);
        return (
          blob &&
          needles.some((n) =>
            new RegExp(
              `(?<![\\w-])${n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?![\\w-])`,
            ).test(blob),
          )
        );
      })
      .map((app) => app.label)
      .sort();
    const uses = new Set<string>();
    const ast = ts.createSourceFile(
      component.path,
      source,
      ts.ScriptTarget.Latest,
      true,
    );
    for (const node of ast.statements) {
      if (!ts.isImportDeclaration(node)) continue;
      const bindings = node.importClause?.namedBindings;
      if (!bindings || !ts.isNamedImports(bindings)) continue;
      for (const symbol of bindings.elements) {
        const id = symbolIds.get((symbol.propertyName ?? symbol.name).text);
        if (id && id !== component.id) uses.add(id);
      }
    }
    relationships[component.id] = { uses: [...uses].sort(), usedBy: [] };
    const pkg = distribution.kind === 'styles' ? styles : ui;
    const importPath =
      distribution.kind === 'angular'
        ? pkg.name +
          (distribution.entryPoint === '.'
            ? ''
            : distribution.entryPoint.slice(1))
        : undefined;
    components[component.id] = {
      id: component.id,
      name: component.name,
      path: component.path,
      category: component.category,
      status: governance.status,
      owner: governance.owner,
      metadata: item.metadataPath,
      bemBlock: component.bemBlock,
      primeNg: component.primeNgComponent ?? null,
      scssPath:
        component.scssPath ??
        (distribution.kind === 'styles' ? component.path : null),
      implementation: distribution.kind === 'styles' ? 'CSS' : 'Angular',
      distribution,
      source: { repository: registry.repository, path: component.path },
      docs: {
        baseUrl: registry.operations.storybook,
        sourcePath: item.docsPath,
        componentId: component.id,
      },
      package:
        distribution.kind === 'local'
          ? null
          : {
              name: pkg.name,
              version: pkg.version,
              importPath,
              exportName:
                distribution.kind === 'angular'
                  ? distribution.exportName
                  : undefined,
            },
      usedIn: usedIn[component.id],
    };
    byStatus[governance.status] = (byStatus[governance.status] ?? 0) + 1;
  }
  for (const [id, rel] of Object.entries(relationships))
    for (const dependency of rel.uses)
      relationships[dependency].usedBy.push(id);
  const tokenFiles = filesUnder(
    path.join(root, 'libs/styles/src/01-settings'),
  ).filter((f) => f.endsWith('.scss')).length;
  const tokenNames = new Set<string>();
  for (const file of filesUnder(path.join(root, 'libs/styles/src/01-settings')).filter((f) => f.endsWith('.scss'))) {
    const body = fs.readFileSync(file, 'utf8');
    for (const match of body.matchAll(/^\s*--(?:#\{\$pds-prefix\}-|pds-)([a-z0-9-]+)\s*:/gm))
      tokenNames.add(`--pds-${match[1]}`);
  }
  const annotations = fs.readFileSync(path.join(root, 'libs/ui/src/storybook/tokens.generated.ts'), 'utf8');
  for (const match of annotations.matchAll(/"cssVar": "(--pds-[^"]+)"/g)) tokenNames.add(match[1]);
  outputs.set('tools/devkit/assets/tokens.json', json({ schemaVersion: 1, source: 'libs/styles/src/01-settings + libs/ui/src/storybook/tokens.generated.ts', stylesVersion: styles.version, names: [...tokenNames].sort() }));
  const catalogue = items.map((item) => {
    const summary = components[item.metadata.component.id] as Record<string, any>;
    const mdx = fs.readFileSync(path.join(root, item.docsPath), 'utf8');
    const explicitId = /<Meta\b[^>]*\bid=["']([^"']+)["']/.exec(mdx)?.[1];
    const title = /<Meta\b[^>]*\btitle=["']([^"']+)["']/.exec(mdx)?.[1];
    const storiesPath = path.join(root, item.docsPath.replace(/\.mdx$/, '.stories.ts'));
    const storyId = explicitId ?? (title ?? storyTitle(storiesPath))?.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const docsPath = storyId ? `?path=/docs/${storyId}--docs` : null;
    return {
      id: item.metadata.component.id,
      metadata: item.metadata,
      source: summary['source'],
      package: summary['package'],
      selector: /selector:\s*['"]([^'"]+)/.exec(fs.readFileSync(path.join(root, item.metadata.component.path), 'utf8'))?.[1] ?? null,
      docs: {
        sourcePath: item.docsPath,
        previewUrl: docsPath ? new URL(docsPath, registry.operations.storybook).href : null,
        versionedUrlTemplate: docsPath ? `${registry.operations.storybook.replace(/\/$/, '')}/releases/{version}/${docsPath}` : null,
        availability: 'preview',
      },
    };
  });
  outputs.set('tools/devkit/assets/catalogue.json', json({ schemaVersion: 1, kind: 'toolkit-snapshot', toolkitVersion: JSON.parse(fs.readFileSync(path.join(root, 'tools/devkit/package.json'), 'utf8')).version, sourceRepository: registry.repository, components: catalogue }));
  for (const name of ['process', 'compatibility', 'registry'])
    outputs.set(`tools/devkit/assets/${name}.json`, json(JSON.parse(fs.readFileSync(path.join(root, `.ai/contracts/${name}.json`), 'utf8'))));
  outputs.set(
    '.ai/contracts/index.json',
    json({
      schemaVersion: 1,
      kind: 'source-inventory',
      meta: {
        framework: 'angular',
        componentLibrary: 'primeng',
        designSystem: 'plectrum',
        prefix: 'pds',
        baseRemPx: 14,
        generator: 'tools/contracts/generate.ts',
      },
      workspace: {
        ...config.workspace,
        apps: registry.applications
          .filter((a) => a.kind === 'local-demo')
          .map((a) => ({ name: a.id, path: a.path })),
      },
      usageProvenance: {
        kind: 'local-source-scan',
        applications: [...sourceBlobs.keys()],
        limitations: [
          'Source references may include unused imports or comments.',
          'External applications are collected from reviewed adoption reports. A missing report does not prove non-adoption.',
        ],
      },
      usedIn,
      tokenArchitecture: config.tokenArchitecture,
      components,
      relationships,
      summary: {
        totalComponents: items.length,
        componentsWithMetadata: items.length,
        relationshipsMapped: Object.values(relationships).reduce(
          (n, r) => n + r.uses.length,
          0,
        ),
        tokenFiles,
        primeNgMappings: items.filter(
          (i) => i.metadata.component.primeNgComponent,
        ).length,
        byStatus,
      },
    }),
  );
  for (const [name, schema] of Object.entries(exchangeSchemas))
    outputs.set(
      `.ai/contracts/schema/json/${name}.v1.schema.json`,
      json({ ...z.toJSONSchema(schema), $id: `urn:plectrum:schema:${name}:1` }),
    );
  for (const [name, schema] of Object.entries(exchangeSchemas))
    outputs.set(`tools/devkit/assets/schema/${name}.v1.schema.json`, json({ ...z.toJSONSchema(schema), $id: `urn:plectrum:schema:${name}:1` }));
  for (const group of ['rules', 'skills', 'contracts/protocols']) {
    for (const file of filesUnder(path.join(root, '.ai', group)).filter((f) => f.endsWith('.md'))) {
      outputs.set(`tools/devkit/rules/central/${group}/${path.basename(file)}`, fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n'));
    }
  }
  checkBoundaries(
    root,
    items,
    new Map([...exports.keys()].map((entry) => [entry, entryBarrel(entry)])),
    outputs,
    ui.name,
  );
  const changed: string[] = [];
  // Retiring the last component in a secondary entry must also retire that entry.
  // Only remove files with our marker and the exact companion config we generate.
  for (const absolute of filesUnder(path.join(root, 'libs/ui/src')).filter(
    (f) => /[\\/]patterns-[a-z0-9-]+-api\.ts$/.test(f),
  )) {
    const file = posix(path.relative(root, absolute));
    if (
      outputs.has(file) ||
      !fs.readFileSync(absolute, 'utf8').startsWith(generated.trimEnd())
    )
      continue;
    const owner = path
      .basename(file)
      .slice('patterns-'.length, -'-api.ts'.length);
    const configFile = `libs/ui/patterns/${owner}/ng-package.json`;
    const configPath = path.join(root, configFile);
    const expected = {
      lib: { entryFile: posix(path.relative(path.dirname(configFile), file)) },
    };
    if (
      fs.existsSync(configPath) &&
      JSON.stringify(JSON.parse(fs.readFileSync(configPath, 'utf8'))) !==
        JSON.stringify(expected)
    )
      throw new Error(`Retired entry has custom configuration: ${configFile}`);
    changed.push(file, configFile);
    if (!check) {
      fs.rmSync(absolute);
      fs.rmSync(configPath, { force: true });
    }
  }
  for (const [file, content] of outputs) {
    const absolute = path.join(root, file);
    if (
      fs.existsSync(absolute) &&
      fs.readFileSync(absolute, 'utf8').replaceAll('\r\n', '\n') === content
    )
      continue;
    changed.push(file);
    if (!check) {
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
      fs.writeFileSync(absolute, content);
    }
  }
  if (check && changed.length)
    throw new Error(
      `Generated artifacts are stale:\n${changed.join('\n')}\nRun npm run contracts:generate`,
    );
  return changed;
}

if (require.main === module)
  generateContracts(process.cwd(), process.argv.includes('--check'))
    .then((files) =>
      console.log(
        `Contracts: ${files.length} artifact(s) updated; inventory and exports verified.`,
      ),
    )
    .catch((error) => {
      console.error(error);
      process.exitCode = 1;
    });
