// Writes the Core dashboard data module from this checkout:
//   npm run insights:generate
// Output: apps/dashboard/src/app/design-system/data/insights.generated.ts
// (gitignored). Facts only and deterministic for a given HEAD: generatedAt is the
// HEAD commit time, every date comes from git or a record, arrays are sorted.
// Recommendation ages are computed live in the browser (libs/insights).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { PlectrumInsights } from '../../libs/insights/src/insights.types';
import { readRegistry } from '../contracts/validate';
import { inventory } from '../contracts/inventory';
import { STALE_AFTER_DAYS, aggregateAdoption, readAdoptionReports } from '../adoption/records';
import {
  FILES,
  REPORTED_NOTE_EMPTY,
  candidates,
  catalogueHistory,
  components,
  mcpTools,
  readJson,
  releases,
  reportedHistory,
  scanHistory,
  searchEval,
  tokens,
  usageFacts,
} from './collect';
import { DEMO_NOTE, demoReports } from './demo';
import { head as headCommit, historyAvailable as hasHistory } from './history';
import type { Catalogue } from './similarity';

export const OUTPUT = 'apps/dashboard/src/app/design-system/data/insights.generated.ts';

export async function buildInsights(root = process.cwd()): Promise<PlectrumInsights> {
  const registry = readRegistry(root);
  const head = headCommit(root);
  const withHistory = hasHistory(root);
  const catalogue = readJson<Catalogue>(root, FILES.catalogue);
  const knownIds = new Set((await inventory(root)).map((item) => item.metadata.component.id));
  const storybook = registry.operations.storybook;

  const current = readAdoptionReports(root);
  const aggregate = aggregateAdoption(current.values(), registry, new Date(head.at));
  const reportedNote = aggregate.reported.length
    ? `${aggregate.reported.length} of ${registry.applications.length} applications sent a reviewed usage report (.ai/adoption).`
    : REPORTED_NOTE_EMPTY;

  return {
    schemaVersion: 1,
    generatedAt: head.at,
    revision: head.sha,
    repository: registry.repository,
    links: { storybook, dashboard: new URL('../dashboard/', storybook).href },
    versions: {
      runtime: readJson<{ version: string }>(root, 'libs/ui/package.json').version,
      toolkit: readJson<{ version: string }>(root, 'tools/devkit/package.json').version,
    },
    historyAvailable: withHistory,
    repo: {
      components: components(root, registry, catalogue),
      scanHistory: withHistory ? scanHistory(root, registry) : [],
      catalogueHistory: withHistory ? catalogueHistory(root) : [],
      searchEval: searchEval(root, withHistory),
      candidates: candidates(root, withHistory),
      tokens: await tokens(root, withHistory),
      releases: releases(root, head, withHistory),
      mcpTools: mcpTools(root),
    },
    usage: {
      reported: await usageFacts('reported', reportedNote, STALE_AFTER_DAYS, registry, reportedHistory(root, registry, withHistory), catalogue),
      demo: await usageFacts('demo', DEMO_NOTE, STALE_AFTER_DAYS, registry, await demoReports(root, { registry, head, catalogue, knownIds }), catalogue),
    },
  };
}

export function renderModule(insights: PlectrumInsights): string {
  return [
    '// Generated by npm run insights:generate (tools/insights/generate.ts). Do not edit; gitignored.',
    `// Facts of ${insights.revision.slice(0, 7)} (${insights.generatedAt}). usage.demo is invented: tools/insights/demo/seed.json.`,
    "import type { PlectrumInsights } from '@pds-internal/insights';",
    '',
    `export const INSIGHTS: PlectrumInsights = ${JSON.stringify(insights, null, 2)};`,
    '',
  ].join('\n');
}

export function summary(insights: PlectrumInsights): string {
  const { repo, usage } = insights;
  const byStatus = repo.components.reduce<Record<string, number>>((acc, item) => ({ ...acc, [item.status]: (acc[item.status] ?? 0) + 1 }), {});
  const usageLine = (name: string, facts: PlectrumInsights['usage']['demo']) =>
    `  usage.${name}: ${facts.applications.filter((app) => app.reportedAt).length}/${facts.applications.length} apps reporting, ${facts.observations.length} observations, ${facts.agentHistory.length} agent points, ${facts.localComponents.length} local components, ${facts.similarity.length} similar pairs`;
  return [
    `Dashboard data ${insights.revision.slice(0, 7)} (${insights.generatedAt}), history ${insights.historyAvailable ? 'available' : 'unavailable (shallow clone)'}:`,
    `  components: ${repo.components.length} (${Object.entries(byStatus).map(([status, count]) => `${status} ${count}`).join(', ')})`,
    `  history: scan ${repo.scanHistory.length}, catalogue ${repo.catalogueHistory.length}, search eval ${repo.searchEval.history.length} points`,
    `  search eval: ${repo.searchEval.passed}/${repo.searchEval.total} (${repo.searchEval.rate}%), ${repo.searchEval.regressions.length} regressions, ${repo.searchEval.knownMisses.length} known misses`,
    `  candidates: ${repo.candidates.length} (${repo.candidates.map((item) => `${item.id} ${item.stage}`).join(', ') || 'none'})`,
    `  tokens: ${repo.tokens.names} names, sync ${repo.tokens.sync?.stage ?? 'none'}, ${repo.tokens.proposals.count} code-owned proposals since ${repo.tokens.proposals.since ?? 'n/a'}`,
    `  releases: ${repo.releases.tags.length} tags (last ${repo.releases.tags.at(-1)?.tag ?? 'none'}), ${repo.releases.pending.length} pending changesets`,
    `  mcp tools: ${repo.mcpTools.join(', ')}`,
    usageLine('reported', usage.reported),
    usageLine('demo', usage.demo),
  ].join('\n');
}

export async function generate(root = process.cwd()): Promise<PlectrumInsights> {
  const insights = await buildInsights(root);
  const target = path.join(root, OUTPUT);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, renderModule(insights));
  console.log(`Wrote ${OUTPUT}\n${summary(insights)}`);
  return insights;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generate().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
