// Figures for Docs/AI strategy (ai-strategy.mdx). Hidden from the sidebar.
import type { Meta, StoryObj } from '@storybook/angular-vite';
import { calloutStory, cardsStory, stepsStory } from './docs-figure-stories';

const meta: Meta = {
  title: 'Docs/AI strategy/Figures',
  tags: ['!dev'],
  parameters: { layout: 'padded' },
};

export default meta;

export const QueryOrder: StoryObj = stepsStory([
  {
    who: 'Agent',
    tone: 'design',
    title: 'Check PrimeNG and Figma first',
    detail:
      'PrimeNG MCP for an existing control. Figma MCP for the Plectrum UI Kit node. Reuse before inventing.',
  },
  {
    who: 'Agent',
    tone: 'system',
    title: 'Load the index',
    detail:
      '.ai/contracts/index.json is the offline map: paths, BEM, PrimeNG wraps, uses / usedBy, status, owner. Always available.',
  },
  {
    who: 'Agent',
    tone: 'app',
    title: 'Query Storybook MCP when it is up',
    detail:
      'npm run storybook exposes http://localhost:6006/mcp. docs-list / docs-show are the live catalogue. Fall back to the index when the server is down.',
  },
  {
    who: 'Agent',
    tone: 'system',
    title: 'Read one metadata file',
    detail:
      'Only the colocated .metadata.ts for the component about to be used or created. Do not load every contract.',
  },
  {
    who: 'CI',
    tone: 'neutral',
    title: 'Regenerate and verify',
    detail:
      'pds:component and the afterFileEdit hook regenerate index.json; CI fails a stale index, a hand-written docs copy (docs:check), or props drift (contracts:check). Play tests stay on the test-runner — MCP does not run them.',
  },
]);

export const Roles: StoryObj = cardsStory([
  {
    eyebrow: 'Agent',
    tone: 'system',
    title: 'Reads contracts first',
    items: [
      'Loads index.json, then Storybook MCP when Storybook is running, then one .metadata.ts',
      'Queries PrimeNG MCP and Figma MCP before creating a component',
      'Uses docs-show before inventing a prop; does not invent tokens or BEM names',
    ],
  },
  {
    eyebrow: 'Author',
    tone: 'app',
    title: 'Owns the component contract',
    items: [
      'Runs pds:component, fills usage / tokens.consumed / aiHints',
      'MDX embeds Status / contract figures — no second prose copy',
      'Regenerates index.json after add or remove',
    ],
  },
  {
    eyebrow: 'Architect',
    tone: 'neutral',
    title: 'Owns schema and protocols',
    items: [
      'Changes ComponentMetadata only in .ai/contracts/schema/',
      'Updates protocols when the workflow changes',
      'Keeps token scripts, docs:check, contracts:check and CI as the contract gates',
    ],
  },
]);

export const Layers: StoryObj = cardsStory([
  {
    title: 'Index — what and where',
    lead: '.ai/contracts/index.json. Regenerated by npm run generate-index from libs/ui. Inventory, relationships, BEM, status, owner. Offline map — Storybook MCP does not replace it.',
  },
  {
    title: 'Metadata — how and why',
    lead: 'Colocated {name}.metadata.ts typed as ComponentMetadata. Use cases, anti-patterns, tokens.consumed, a11y, aiHints. Docs pages embed it through pds-docs-status / pds-docs-contract. Scaffolded by npm run pds:component.',
  },
  {
    title: 'Protocols — rules',
    lead: 'Markdown in .ai/contracts/protocols/. Decision trees for create / query / audit, including Storybook MCP tools. Schema in .ai/contracts/schema/ is the TypeScript shape.',
  },
]);

export const Rules: StoryObj = cardsStory([
  {
    title: 'Contracts are code',
    lead: 'Metadata is TypeScript imported as @solidaris/contracts. A missing or stale .metadata.ts is a defect, not optional docs.',
  },
  {
    title: 'Index is generated',
    lead: 'Do not edit index.json by hand. pds:component and a Cursor hook regenerate it; CI fails when the committed file is stale. A manual run is only needed after deleting files by hand.',
  },
  {
    title: 'tokens.consumed is checked',
    lead: 'Foundations / Token contracts compares each metadata list to the compiled CSS. The Consumed play test fails undeclared tokens in CI (test-storybook:ci).',
  },
  {
    title: 'props match the class',
    lead: 'npm run contracts:check compares .metadata.ts props to Angular input / model / output. Name, required, type, and literal default must match.',
  },
  {
    title: 'PrimeNG first',
    lead: 'No new Angular wrapper when PrimeNG already owns the behaviour. BEMIT classes and 01-settings bridges restyle; they do not fork the control.',
  },
  {
    title: 'Metadata is the docs SSOT',
    lead: 'pds-docs-status and pds-docs-contract render the metadata on the component page. MDX embeds those figures and adds canvases; it does not restate the blocks. npm run docs:check fails a hand-written copy.',
  },
  {
    title: 'Scaffold, then fill',
    lead: 'pds:component writes the stub files including .metadata.ts. Fill usage, tokens and aiHints before marking the component done.',
  },
  {
    title: 'Storybook MCP is live, not the scaffolder',
    lead: 'docs-list / docs-show / stories-preview need npm run storybook. They do not replace pds:component, index.json, or npm run test-storybook.',
  },
]);

export const Gaps: StoryObj = calloutStory({
  tone: 'info',
  title: 'Not automated yet',
  items: [
    '@storybook/angular-vite stays in preview until Storybook 11.',
    'Storybook MCP’s test toolset needs the Vitest addon; this workspace keeps @storybook/test-runner.',
    'tokens.consumed is gated one way (listed but not declared). Unused tokens in SCSS are not gated.',
  ],
});
