// Figures for Docs/AI strategy (ai-strategy.mdx). Hidden from the sidebar.
import type { Meta, StoryObj } from '@storybook/angular';
import { calloutStory, cardsStory, stepsStory } from './docs-figure-stories';

const meta: Meta = {
  title: 'Docs/AI strategy/Figures',
  tags: ['!dev'],
  parameters: { layout: 'padded' },
};

export default meta;

export const QueryOrder: StoryObj = stepsStory([
  { who: 'Agent', tone: 'system', title: 'Load the index', detail: '.ai/contracts/index.json is the workspace map: components, paths, BEM blocks, PrimeNG wraps, uses / usedBy.' },
  { who: 'Agent', tone: 'system', title: 'Read one metadata file', detail: 'Only the colocated .metadata.ts for the component about to be used or created. Do not load every contract.' },
  { who: 'Agent', tone: 'design', title: 'Check PrimeNG and Figma first', detail: 'PrimeNG MCP for an existing control. Figma MCP for the Plectrum UI Kit node. Reuse before inventing.' },
  { who: 'Agent', tone: 'system', title: 'Follow a protocol', detail: 'component-creation.md, query-protocol.md or token-audit.md. Rules in .ai/rules stay hard stops.' },
  { who: 'CI', tone: 'neutral', title: 'Regenerate and verify', detail: 'pds:component and the afterFileEdit hook regenerate index.json automatically; CI fails when the committed file is stale. Token scripts and Storybook stay the human-visible contract.' },
]);

export const Roles: StoryObj = cardsStory([
  {
    eyebrow: 'Agent', tone: 'system', title: 'Reads contracts first',
    items: [
      'Loads index.json, then one .metadata.ts, then a protocol',
      'Queries PrimeNG MCP and Figma MCP before creating a component',
      'Does not invent tokens, BEM names or a second catalogue',
    ],
  },
  {
    eyebrow: 'Author', tone: 'app', title: 'Owns the component contract',
    items: [
      'Runs pds:component, fills usage / tokens.consumed / aiHints',
      'Keeps CSF + attached MDX as the human-facing docs',
      'Regenerates index.json after add or remove',
    ],
  },
  {
    eyebrow: 'Architect', tone: 'neutral', title: 'Owns schema and protocols',
    items: [
      'Changes ComponentMetadata only in .ai/contracts/schema/',
      'Updates protocols when the workflow changes',
      'Keeps token scripts and CI as the token contract',
    ],
  },
]);

export const Layers: StoryObj = cardsStory([
  {
    title: 'Index — what and where',
    lead: '.ai/contracts/index.json. Regenerated by npm run generate-index from libs/ui. Inventory, relationships, metadata presence. Not a substitute for the TypeScript API.',
  },
  {
    title: 'Metadata — how and why',
    lead: 'Colocated {name}.metadata.ts typed as ComponentMetadata. Use cases, anti-patterns, tokens.consumed, a11y, aiHints. Scaffolded by npm run pds:component.',
  },
  {
    title: 'Protocols — rules',
    lead: 'Markdown in .ai/contracts/protocols/. Decision trees for create / query / audit. Schema in .ai/contracts/schema/ is the TypeScript shape.',
  },
]);

export const Rules: StoryObj = cardsStory([
  { title: 'Contracts are code', lead: 'Metadata is TypeScript imported as @solidaris/contracts. A missing or stale .metadata.ts is a defect, not optional docs.' },
  { title: 'Index is generated', lead: 'Do not edit index.json by hand. pds:component and a Cursor hook regenerate it; CI fails when the committed file is stale. A manual run is only needed after deleting files by hand.' },
  { title: 'tokens.consumed is checked', lead: 'Foundations / Token contracts compares each metadata list to the compiled CSS. A not-declared row is a broken contract.' },
  { title: 'PrimeNG first', lead: 'No new Angular wrapper when PrimeNG already owns the behaviour. BEMIT classes and 01-settings bridges restyle; they do not fork the control.' },
  { title: 'Storybook is the catalogue', lead: 'CSF + attached MDX remain the designer-facing docs. Metadata is for agents and audits, not a second prose surface.' },
  { title: 'Scaffold, then fill', lead: 'pds:component writes the stub files including .metadata.ts. Fill usage, tokens and aiHints before marking the component done.' },
]);

export const Gaps: StoryObj = calloutStory({
  tone: 'info',
  title: 'Not automated yet',
  items: [
    'No check that .metadata.ts props match the Angular inputs. Compodoc or the Angular compiler is the likely base.',
    'Storybook does not render the full metadata object on the docs page. Token contracts covers tokens.consumed only.',
    'Storybook MCP (components manifest for agents) needs the angular-vite builder; this workspace runs the webpack builder, so index.json stays the agent-facing map.',
  ],
});
